// MMO2 1.49 visual state player + NPC interaction. Server still owns game authority.
(function(){
'use strict';
const NPCS={town_talking:[['100','雜貨商人','shop'],['118','倉庫管理員','warehouse']],town_silver_knight:[['100','武器商人','shop'],['118','倉庫管理員','warehouse']],town_elf:[['100','妖精商人','shop'],['118','倉庫管理員','warehouse']],town_gludio:[['100','雜貨商人','shop'],['118','倉庫管理員','warehouse']],town_gludin:[['100','武器商人','shop'],['118','倉庫管理員','warehouse']]};
const CLASS_FOLDER={royal:'王子',knight:'男騎士',mage:'男法師',elf:'男妖精'};
const MOB_NAMES={orc:'妖魔',goblin:'哥布林',orc_archer:'妖魔弓箭手',gremlin:'格利芬',zombie:'殭屍',wolf:'狼',skeleton:'骷髏',fighter:'妖魔鬥士',stone_golem:'石頭高崙',spider:'蜘蛛',ghoul:'食屍鬼',sparto:'史巴托',lycan:'狼人',gaster:'卡司特',orc_mage:'妖魔法師',hobgoblin:'哈柏哥布林',bear:'熊',lizardman:'蜥蜴人',ant:'螞蟻',giant_ant:'巨大螞蟻',scorpion:'蠍子',evil_lizard:'邪惡蜥蜴',skel_archer:'骷髏弓箭手',skel_spear:'骷髏槍兵',skel_axe:'骷髏斧兵',ogre:'歐吉',cerberus:'地獄犬',elder:'長者',necromancer:'死靈法師',dk:'死亡騎士',black_knight:'黑騎士',b_knight:'黑騎士',kurt:'克特',dark_elf:'黑暗妖精',ogre_warrior:'歐吉戰士',arian:'亞力安',wyvern:'飛龍',blackelder:'黑長者',dragon:'巨龍',ant_queen:'巨大蟻后'};
const ITEM_NAMES={potion_red:'紅色藥水',potion_orange:'橙色藥水',potion_clear:'白色藥水',wpn_5:'箭',wpn_22:'銀箭',scroll_weapon:'對武器施法的卷軸',scroll_armor:'對盔甲施法的卷軸',item_dagger:'匕首',item_sword:'長劍',item_bow:'獵人之弓',item_staff:'魔杖',item_leather_armor:'皮甲',item_chain_mail:'鎖子甲',item_helmet:'頭盔',item_shield:'盾牌',skillbook_light:'魔法書(光箭)',skillbook_heal:'魔法書(初級治癒術)'};
const SHOP=[['potion_red',45],['potion_orange',180],['potion_clear',550],['wpn_5',1],['wpn_22',2],['item_dagger',50],['item_sword',900],['item_bow',1200],['item_staff',1000],['item_leather_armor',700],['item_chain_mail',3500],['item_helmet',800],['item_shield',1000],['skillbook_light',1000],['skillbook_heal',1200]];
const npcFrames=new Map(),animCache=new Map(),loadingAnim=new Set(),mobState=new Map(),classAnimCache=new Map(),classLoading=new Set();
let tick=0,lastNpcMap='',lastSelfHp=null,playerAttackTimer=null,playerAttackFrame=0,playerAttacking=false;
function enc(s){return encodeURI(s)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function pathNpc(id,i){return enc(`assets/npc/${id}/idle_${i}.png`)}
function pathMob(folder,kind,i){return enc(`assets/anim/${folder}/${kind}_${i}.png`)}
function pathClass(folder,prefix,i){return enc(`assets/classanim/${folder}/${prefix}_${i}.png`)}
function imageExists(src){return new Promise(resolve=>{let im=new Image();im.onload=()=>resolve(true);im.onerror=()=>resolve(false);im.src=src;});}
async function getNpcFrames(id){if(npcFrames.has(id))return npcFrames.get(id);let count=1;try{let r=await fetch(`assets/npc/${encodeURIComponent(id)}/meta.json`,{cache:'force-cache'});if(r.ok){let j=await r.json();count=Math.max(1,Number(j?.files?.idle?.frames)||1)}}catch(_){}npcFrames.set(id,count);return count;}
async function discoverAnim(folder,kind){const key=folder+'|'+kind;if(animCache.has(key)||loadingAnim.has(key))return;loadingAnim.add(key);let arr=[];for(let i=0;i<32;i++){let src=pathMob(folder,kind,i);if(await imageExists(src))arr.push(src);else break;}animCache.set(key,arr);loadingAnim.delete(key);}
function frames(folder,kind){discoverAnim(folder,kind);return animCache.get(folder+'|'+kind)||[];}
async function discoverClassAnim(folder){if(classAnimCache.has(folder)||classLoading.has(folder))return;classLoading.add(folder);const prefixes=['blunt_attack','sword_attack','bow_attack','staff_attack','magic_attack','attack'];let best=[];for(const prefix of prefixes){let arr=[];for(let i=0;i<20;i++){let src=pathClass(folder,prefix,i);if(await imageExists(src))arr.push(src);else break;}if(arr.length>best.length)best=arr;if(arr.length>=4)break;}classAnimCache.set(folder,best);classLoading.delete(folder);}
function setMobState(uid,kind,duration=0){let s=mobState.get(uid)||{kind:'idle',frame:0,until:0,locked:false};if(s.kind!==kind){s.kind=kind;s.frame=0;}s.until=duration?Date.now()+duration:0;s.locked=kind==='death';mobState.set(uid,s);}
function syncMobStates(snapshot){const mobs=snapshot?.world?.mobs||[],ids=new Set();for(const m of mobs){ids.add(m.uid);let s=mobState.get(m.uid);if(!s){s={kind:m.dead?'death':'idle',frame:0,until:0,locked:!!m.dead,lastHp:m.hp,folder:MOB_NAMES[m.templateId]||m.templateId};mobState.set(m.uid,s);}s.folder=MOB_NAMES[m.templateId]||m.templateId;if(m.dead){s.kind='death';s.locked=true;s.until=0;}else if(s.locked){s.kind='idle';s.frame=0;s.locked=false;}if(!m.dead&&s.lastHp!=null&&m.hp<s.lastHp){s.kind='hurt';s.frame=0;s.until=Date.now()+360;}s.lastHp=m.hp;for(const k of ['idle','attack','hurt','death'])discoverAnim(s.folder,k);}for(const uid of [...mobState.keys()])if(!ids.has(uid))mobState.delete(uid);const hp=snapshot?.self?.hp;if(lastSelfHp!=null&&hp<lastSelfHp){const alive=mobs.filter(m=>!m.dead);if(alive.length)setMobState(alive[Math.floor(Math.random()*alive.length)].uid,'attack',650);}lastSelfHp=hp;}
function handleEvent(evt,snapshot){if(!evt)return;if(evt.type==='attack'&&evt.target){if(evt.kill)setMobState(evt.target,'death');else if(evt.hit)setMobState(evt.target,'hurt',360);}if(evt.type==='tick')syncMobStates(snapshot);}
async function renderNpcCards(map){let box=document.getElementById('npc-layer');if(!box)return;let rows=NPCS[map]||[];if(!rows.length){box.innerHTML='';lastNpcMap=map;return;}if(lastNpcMap!==map||box.children.length!==rows.length){box.innerHTML=rows.map(n=>`<button class="npc-card" data-npc-id="${n[0]}" data-npc-action="${n[2]}" data-npc-name="${esc(n[1])}" type="button"><img class="npc-sprite" src="${pathNpc(n[0],0)}"><b>${esc(n[1])}</b><small style="display:block;color:#93c5fd;margin-top:4px">點擊互動</small></button>`).join('');box.querySelectorAll('.npc-card').forEach(card=>card.onclick=()=>openNpc(card.dataset.npcAction,card.dataset.npcName));lastNpcMap=map;}for(const card of box.querySelectorAll('[data-npc-id]')){let id=card.dataset.npcId,count=await getNpcFrames(id),img=card.querySelector('.npc-sprite');if(img)img.src=pathNpc(id,tick%count);}}
function animateMobs(){let snap=window.MMO149Realtime?.snapshot?.();syncMobStates(snap);const mobs=snap?.world?.mobs||[],cards=document.querySelectorAll('#mob-list .mob-card');cards.forEach((card,i)=>{let mob=mobs[i],img=card.querySelector('.mob-sprite');if(!mob||!img)return;let s=mobState.get(mob.uid);if(!s)return;if(mob.dead||s.kind==='death'){let death=frames(s.folder,'death');let still=death.length?death[death.length-1]:pathMob(s.folder,'death',0);card.style.setProperty('--death-img',`url("${still}")`);card.classList.add('death-static');card.dataset.anim='death';img.style.opacity='0';return;}card.classList.remove('death-static');img.style.opacity='1';if(s.until&&Date.now()>s.until&&!s.locked){s.kind='idle';s.frame=0;s.until=0;}let fs=frames(s.folder,s.kind);if(!fs.length&&s.kind!=='idle')fs=frames(s.folder,'idle');if(!fs.length)fs=frames(s.folder,'attack');if(!fs.length)return;img.src=fs[s.frame%fs.length];s.frame=(s.frame+1)%fs.length;card.dataset.anim=s.kind;});}
function ensurePlayerStage(){let world=document.querySelector('.world');if(!world)return null;let stage=document.getElementById('battle-player');if(stage)return stage;stage=document.createElement('div');stage.id='battle-player';stage.innerHTML='<img id="battle-player-img" alt="player"><span id="battle-player-name"></span>';let mobs=document.getElementById('mob-list');world.insertBefore(stage,mobs||null);return stage;}
function updatePlayerSprite(){const snap=window.MMO149Realtime?.snapshot?.(),self=snap?.self;if(!self)return;let stage=ensurePlayerStage(),img=document.getElementById('battle-player-img'),name=document.getElementById('battle-player-name');if(!stage||!img)return;const folder=CLASS_FOLDER[self.cls]||'男騎士';discoverClassAnim(folder);const arr=classAnimCache.get(folder)||[];stage.dataset.cls=self.cls||'';if(name)name.textContent=self.name||'';if(!playerAttacking&&arr.length)img.src=arr[0];}
function animatePlayer(){const snap=window.MMO149Realtime?.snapshot?.(),self=snap?.self;if(!self)return;const folder=CLASS_FOLDER[self.cls]||'男騎士';discoverClassAnim(folder);const arr=classAnimCache.get(folder)||[];if(!arr.length){setTimeout(animatePlayer,120);return;}let img=document.getElementById('battle-player-img');if(!img){ensurePlayerStage();img=document.getElementById('battle-player-img');}if(!img)return;clearInterval(playerAttackTimer);playerAttacking=true;playerAttackFrame=0;playerAttackTimer=setInterval(()=>{img.src=arr[Math.min(playerAttackFrame,arr.length-1)];playerAttackFrame++;if(playerAttackFrame>=arr.length){clearInterval(playerAttackTimer);playerAttackTimer=null;playerAttacking=false;img.src=arr[0];}},75);}
function ensureNpcDialog(){let d=document.getElementById('npc-dialog');if(d)return d;d=document.createElement('div');d.id='npc-dialog';d.style.cssText='position:fixed;inset:0;background:#0009;z-index:9999;display:none;align-items:center;justify-content:center;padding:20px';d.innerHTML='<div style="width:min(620px,94vw);max-height:82vh;overflow:auto;background:#0b1724;border:1px solid #b58a42;border-radius:12px;padding:18px"><div style="display:flex;justify-content:space-between"><h2 id="npc-dialog-title" style="margin:0;color:#fde68a"></h2><button class="btn" id="npc-dialog-close">關閉</button></div><div id="npc-dialog-body" style="margin-top:14px"></div></div>';document.body.appendChild(d);d.querySelector('#npc-dialog-close').onclick=()=>d.style.display='none';d.onclick=e=>{if(e.target===d)d.style.display='none'};return d;}
function qtyInput(id){return `<input id="${id}" type="number" min="1" max="9999" value="1" style="width:72px;background:#111827;border:1px solid #475569;color:white;padding:7px;border-radius:5px">`}
function openNpc(action,name){let d=ensureNpcDialog(),body=d.querySelector('#npc-dialog-body');d.querySelector('#npc-dialog-title').textContent=name||'NPC';d.style.display='flex';if(action==='shop'){body.innerHTML='<p style="color:#94a3b8">由伺服器結算金幣與物品。</p>'+SHOP.map(([id,price],i)=>`<div style="display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #263548"><span>${esc(ITEM_NAMES[id]||id)} <small style="color:#facc15">${price.toLocaleString()} 金幣</small></span>${qtyInput('shop-q-'+i)}<button class="btn" data-buy="${id}" data-q="shop-q-${i}">購買</button></div>`).join('');body.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>window.MMO149Realtime?.buy?.(b.dataset.buy,Math.max(1,Number(document.getElementById(b.dataset.q)?.value)||1)));return;}if(action==='warehouse'){renderWarehouse(body);return;}body.innerHTML='<p>目前沒有可用功能。</p>';}
function renderWarehouse(body){let c=window.MMO149Realtime?.snapshot?.()?.self||{},inv=c.inventory||[],wh=c.warehouse||[];const row=(it,mode)=>`<div style="display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #263548"><span>${esc(ITEM_NAMES[it.id]||it.id)} x${it.cnt||1}</span><button class="btn" data-wh="${mode}" data-uid="${esc(it.uid)}">${mode==='deposit'?'存入 1 個':'取出 1 個'}</button></div>`;body.innerHTML='<h3 style="color:#93c5fd">背包 → 倉庫</h3>'+(inv.length?inv.map(i=>row(i,'deposit')).join(''):'<div class="empty">背包沒有物品</div>')+'<h3 style="color:#93c5fd;margin-top:18px">倉庫 → 背包</h3>'+(wh.length?wh.map(i=>row(i,'withdraw')).join(''):'<div class="empty">倉庫沒有物品</div>');body.querySelectorAll('[data-wh]').forEach(b=>b.onclick=()=>window.MMO149Realtime?.warehouse?.(b.dataset.wh,b.dataset.uid,1));}
function refreshOpenNpc(){let d=document.getElementById('npc-dialog');if(!d||d.style.display!=='flex')return;let title=d.querySelector('#npc-dialog-title')?.textContent||'';if(title.includes('倉庫'))renderWarehouse(d.querySelector('#npc-dialog-body'));}
function onSnapshot(snapshot){syncMobStates(snapshot);handleEvent(snapshot?.event,snapshot);updatePlayerSprite();refreshOpenNpc();}
function injectStyles(){let s=document.createElement('style');s.textContent='.world{position:relative}.mob-card.death-static{position:relative}.mob-card.death-static::before{content:"";width:100px;height:100px;background-image:var(--death-img);background-position:center;background-repeat:no-repeat;background-size:contain;image-rendering:pixelated;display:block}.mob-card.death-static .mob-sprite{display:none!important}#battle-player{position:absolute;left:18px;bottom:32px;width:130px;z-index:3;text-align:center;pointer-events:none;filter:drop-shadow(0 5px 7px #000)}#battle-player-img{width:110px;height:110px;object-fit:contain;image-rendering:pixelated;display:block;margin:auto}#battle-player-name{display:inline-block;background:#07111dcc;border:1px solid #475569;border-radius:4px;padding:2px 6px;font-size:12px;color:#fde68a}@media(max-width:760px){#battle-player{position:relative;left:auto;bottom:auto;width:100%;display:flex;flex-direction:column;align-items:center;margin:4px auto 10px}#battle-player-img{width:96px;height:96px}}';document.head.appendChild(s);}
function loop(){tick++;let snap=window.MMO149Realtime?.snapshot?.(),map=snap?.world?.map||lastNpcMap;if(map)renderNpcCards(map);animateMobs();updatePlayerSprite();}
window.MMO149Visuals={animatePlayerAttack:animatePlayer,onSnapshot,handleEvent,openNpc};
function patchThinUI(){if(!window.ThinUI)return false;window.ThinUI.animatePlayerAttack=animatePlayer;return true;}
function boot(){injectStyles();ensureNpcDialog();ensurePlayerStage();if(!patchThinUI()){let p=setInterval(()=>{if(patchThinUI())clearInterval(p)},50);}setInterval(loop,140);loop();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
