// MMO2 1.49 visual state player + NPC interaction. Server still owns game authority.
(function(){
'use strict';
const NPCS={
 town_talking:[['100','雜貨商人','shop'],['118','倉庫管理員','warehouse']],
 town_silver_knight:[['100','武器商人','shop'],['118','倉庫管理員','warehouse']],
 town_elf:[['100','妖精商人','shop'],['118','倉庫管理員','warehouse']],
 town_gludio:[['100','雜貨商人','shop'],['118','倉庫管理員','warehouse']],
 town_gludin:[['100','武器商人','shop'],['118','倉庫管理員','warehouse']]
};
const MOB_NAMES={orc:'妖魔',goblin:'哥布林',orc_archer:'妖魔弓箭手',gremlin:'格利芬',zombie:'殭屍',wolf:'狼',skeleton:'骷髏',fighter:'妖魔鬥士',stone_golem:'石頭高崙',spider:'蜘蛛',ghoul:'食屍鬼',sparto:'史巴托',lycan:'狼人',gaster:'卡司特',orc_mage:'妖魔法師',hobgoblin:'哈柏哥布林',bear:'熊',lizardman:'蜥蜴人',ant:'螞蟻',giant_ant:'巨大螞蟻',scorpion:'蠍子',evil_lizard:'邪惡蜥蜴',skel_archer:'骷髏弓箭手',skel_spear:'骷髏槍兵',skel_axe:'骷髏斧兵',ogre:'歐吉',cerberus:'地獄犬',elder:'長者',necromancer:'死靈法師',dk:'死亡騎士',black_knight:'黑騎士',b_knight:'黑騎士',kurt:'克特',dark_elf:'黑暗妖精',ogre_warrior:'歐吉戰士',arian:'亞力安',wyvern:'飛龍',blackelder:'黑長者',dragon:'巨龍',ant_queen:'巨大蟻后'};
const ITEM_NAMES={potion_red:'紅色藥水',potion_orange:'橙色藥水',potion_clear:'白色藥水',wpn_5:'箭',wpn_22:'銀箭',scroll_weapon:'對武器施法的卷軸',scroll_armor:'對盔甲施法的卷軸',item_dagger:'匕首',item_sword:'長劍',item_bow:'獵人之弓',item_staff:'魔杖',item_leather_armor:'皮甲',item_chain_mail:'鎖子甲',item_helmet:'頭盔',item_shield:'盾牌',skillbook_light:'魔法書(光箭)',skillbook_heal:'魔法書(初級治癒術)'};
const SHOP=[['potion_red',45],['potion_orange',180],['potion_clear',550],['wpn_5',1],['wpn_22',2],['item_dagger',50],['item_sword',900],['item_bow',1200],['item_staff',1000],['item_leather_armor',700],['item_chain_mail',3500],['item_helmet',800],['item_shield',1000],['skillbook_light',1000],['skillbook_heal',1200]];
const npcFrames=new Map(),animCache=new Map(),loadingAnim=new Set(),mobState=new Map();
let tick=0,lastNpcMap='',lastSelfHp=null;
function enc(s){return encodeURI(s)}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pathNpc(id,i){return enc(`assets/npc/${id}/idle_${i}.png`)}
function pathMob(folder,kind,i){return enc(`assets/anim/${folder}/${kind}_${i}.png`)}
async function getNpcFrames(id){if(npcFrames.has(id))return npcFrames.get(id);let count=1;try{let r=await fetch(`assets/npc/${encodeURIComponent(id)}/meta.json`,{cache:'force-cache'});if(r.ok){let j=await r.json();count=Math.max(1,Number(j?.files?.idle?.frames)||1)}}catch(_){}npcFrames.set(id,count);return count;}
function imageExists(src){return new Promise(resolve=>{let im=new Image();im.onload=()=>resolve(true);im.onerror=()=>resolve(false);im.src=src;});}
async function discoverAnim(folder,kind){const key=folder+'|'+kind;if(animCache.has(key)||loadingAnim.has(key))return;loadingAnim.add(key);let frames=[];for(let i=0;i<32;i++){let src=pathMob(folder,kind,i);if(await imageExists(src))frames.push(src);else break;}animCache.set(key,frames);loadingAnim.delete(key);}
function frames(folder,kind){discoverAnim(folder,kind);return animCache.get(folder+'|'+kind)||[];}
function setMobState(uid,kind,duration=0){let s=mobState.get(uid)||{kind:'idle',frame:0,until:0,locked:false};if(s.kind!==kind){s.kind=kind;s.frame=0;}s.until=duration?Date.now()+duration:0;s.locked=kind==='death';mobState.set(uid,s);}
function syncMobStates(snapshot){const mobs=snapshot?.world?.mobs||[];const nowIds=new Set();for(const m of mobs){nowIds.add(m.uid);let s=mobState.get(m.uid);if(!s){s={kind:m.dead?'death':'idle',frame:0,until:0,locked:!!m.dead,lastHp:m.hp,folder:MOB_NAMES[m.templateId]||m.templateId};mobState.set(m.uid,s);}s.folder=MOB_NAMES[m.templateId]||m.templateId;if(m.dead&&!s.locked){s.kind='death';s.frame=0;s.locked=true;s.until=0;}else if(!m.dead&&s.locked){s.kind='idle';s.frame=0;s.locked=false;}if(!m.dead&&s.lastHp!=null&&m.hp<s.lastHp){s.kind='hurt';s.frame=0;s.until=Date.now()+360;}s.lastHp=m.hp;for(const k of ['idle','attack','hurt','death'])discoverAnim(s.folder,k);}for(const uid of [...mobState.keys()])if(!nowIds.has(uid))mobState.delete(uid);
const selfHp=snapshot?.self?.hp;if(lastSelfHp!=null&&selfHp<lastSelfHp){const alive=mobs.filter(m=>!m.dead);if(alive.length){const attacker=alive[Math.floor(Math.random()*alive.length)];setMobState(attacker.uid,'attack',650);}}lastSelfHp=selfHp;}
function handleEvent(evt,snapshot){if(!evt)return;if(evt.type==='attack'&&evt.target){if(evt.kill)setMobState(evt.target,'death');else if(evt.hit)setMobState(evt.target,'hurt',360);}if(evt.type==='tick')syncMobStates(snapshot);}
async function renderNpcCards(map){let box=document.getElementById('npc-layer');if(!box)return;let rows=NPCS[map]||[];if(!rows.length){box.innerHTML='';lastNpcMap=map;return;}if(lastNpcMap!==map||box.children.length!==rows.length){box.innerHTML=rows.map(n=>`<button class="npc-card" data-npc-id="${n[0]}" data-npc-action="${n[2]}" data-npc-name="${esc(n[1])}" type="button"><img class="npc-sprite" src="${pathNpc(n[0],0)}" alt="${esc(n[1])}"><b>${esc(n[1])}</b><small style="display:block;color:#93c5fd;margin-top:4px">點擊互動</small></button>`).join('');box.querySelectorAll('.npc-card').forEach(card=>card.onclick=()=>openNpc(card.dataset.npcAction,card.dataset.npcName));lastNpcMap=map;}for(let card of box.querySelectorAll('[data-npc-id]')){let id=card.dataset.npcId,count=await getNpcFrames(id),img=card.querySelector('.npc-sprite');if(img)img.src=pathNpc(id,tick%count);}}
function animateMobs(){let snap=window.MMO149Realtime?.snapshot?.();syncMobStates(snap);const mobs=snap?.world?.mobs||[],cards=document.querySelectorAll('#mob-list .mob-card');cards.forEach((card,i)=>{let mob=mobs[i],img=card.querySelector('.mob-sprite');if(!mob||!img)return;img.dataset.mobUid=mob.uid;let s=mobState.get(mob.uid);if(!s)return;if(s.until&&Date.now()>s.until&&!s.locked){s.kind='idle';s.frame=0;s.until=0;}let fs=frames(s.folder,s.kind);if(!fs.length&&s.kind!=='idle')fs=frames(s.folder,'idle');if(!fs.length)fs=frames(s.folder,'attack');if(!fs.length)return;if(s.kind==='death'){s.frame=Math.min(s.frame,fs.length-1);img.src=fs[s.frame];if(s.frame<fs.length-1)s.frame++;}else{img.src=fs[s.frame%fs.length];s.frame=(s.frame+1)%fs.length;}card.dataset.anim=s.kind;});}
function animatePlayer(){let p=document.getElementById('char-portrait');if(!p)return;p.classList.remove('player-attack');void p.offsetWidth;p.classList.add('player-attack');}
function ensureNpcDialog(){let d=document.getElementById('npc-dialog');if(d)return d;d=document.createElement('div');d.id='npc-dialog';d.style.cssText='position:fixed;inset:0;background:#0009;z-index:9999;display:none;align-items:center;justify-content:center;padding:20px';d.innerHTML='<div style="width:min(620px,94vw);max-height:82vh;overflow:auto;background:#0b1724;border:1px solid #b58a42;border-radius:12px;padding:18px;box-shadow:0 20px 60px #000"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h2 id="npc-dialog-title" style="margin:0;color:#fde68a"></h2><button class="btn" id="npc-dialog-close">關閉</button></div><div id="npc-dialog-body" style="margin-top:14px"></div></div>';document.body.appendChild(d);d.querySelector('#npc-dialog-close').onclick=()=>d.style.display='none';d.onclick=e=>{if(e.target===d)d.style.display='none'};return d;}
function qtyInput(id){return `<input id="${id}" type="number" min="1" max="9999" value="1" style="width:72px;background:#111827;border:1px solid #475569;color:white;padding:7px;border-radius:5px">`}
function openNpc(action,name){let d=ensureNpcDialog(),body=d.querySelector('#npc-dialog-body');d.querySelector('#npc-dialog-title').textContent=name||'NPC';d.style.display='flex';if(action==='shop'){body.innerHTML='<p style="color:#94a3b8">由伺服器結算金幣與物品。</p>'+SHOP.map(([id,price],i)=>`<div style="display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #263548"><span>${esc(ITEM_NAMES[id]||id)} <small style="color:#facc15">${price.toLocaleString()} 金幣</small></span>${qtyInput('shop-q-'+i)}<button class="btn" data-buy="${id}" data-q="shop-q-${i}">購買</button></div>`).join('');body.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{let q=Math.max(1,Number(document.getElementById(b.dataset.q)?.value)||1);window.MMO149Realtime?.buy?.(b.dataset.buy,q);});return;}if(action==='warehouse'){renderWarehouse(body);return;}body.innerHTML='<p>目前沒有可用功能。</p>';}
function renderWarehouse(body){let c=window.MMO149Realtime?.snapshot?.()?.self||{},inv=c.inventory||[],wh=c.warehouse||[];const row=(it,mode)=>`<div style="display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:8px;border-bottom:1px solid #263548"><span>${esc(ITEM_NAMES[it.id]||it.id)} x${it.cnt||1}</span><button class="btn" data-wh="${mode}" data-uid="${esc(it.uid)}">${mode==='deposit'?'存入 1 個':'取出 1 個'}</button></div>`;body.innerHTML='<h3 style="color:#93c5fd">背包 → 倉庫</h3>'+(inv.length?inv.map(i=>row(i,'deposit')).join(''):'<div class="empty">背包沒有物品</div>')+'<h3 style="color:#93c5fd;margin-top:18px">倉庫 → 背包</h3>'+(wh.length?wh.map(i=>row(i,'withdraw')).join(''):'<div class="empty">倉庫沒有物品</div>');body.querySelectorAll('[data-wh]').forEach(b=>b.onclick=()=>window.MMO149Realtime?.warehouse?.(b.dataset.wh,b.dataset.uid,1));}
function refreshOpenNpc(){let d=document.getElementById('npc-dialog');if(!d||d.style.display!=='flex')return;let title=d.querySelector('#npc-dialog-title')?.textContent||'';if(title.includes('倉庫'))renderWarehouse(d.querySelector('#npc-dialog-body'));}
function onSnapshot(snapshot){syncMobStates(snapshot);handleEvent(snapshot?.event,snapshot);refreshOpenNpc();}
function loop(){tick++;let snap=window.MMO149Realtime?.snapshot?.(),map=snap?.world?.map||lastNpcMap;if(map)renderNpcCards(map);animateMobs();}
window.MMO149Visuals={animatePlayerAttack:animatePlayer,onSnapshot,handleEvent,openNpc};
function patchThinUI(){if(!window.ThinUI)return false;window.ThinUI.animatePlayerAttack=animatePlayer;return true;}
function boot(){ensureNpcDialog();if(!patchThinUI()){let p=setInterval(()=>{if(patchThinUI())clearInterval(p)},50);}setInterval(loop,140);loop();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
