// MMO2 1.49 thin client UI. Rendering only; no game authority.
(function(){
'use strict';
const CLASS_NAMES={royal:'王族',knight:'騎士',mage:'法師',elf:'妖精'};
const CLASS_IMG={royal:'assets/character/王子.png',knight:'assets/character/男騎士.png',mage:'assets/character/男法師.png',elf:'assets/character/男妖精.png'};
const MAP_GROUPS={village:[['town_talking','說話之島'],['town_silver_knight','銀騎士村'],['town_elf','妖精森林'],['town_gludio','燃柳村'],['town_gludin','古魯丁村莊']],wild:[['training','新兵修練場'],['talking_island','說話之島周邊'],['talking_island_port','說話之島港口'],['silver_knight','銀騎士地區'],['zone_01','妖精森林周邊'],['elf_forest','妖魔森林'],['gludio','古魯丁'],['windwood','風木'],['desert','沙漠'],['kent','肯特'],['dragon_valley','龍之谷']],dungeon:[['zone_06','古魯丁地監1樓'],['zone_07','古魯丁地監2樓'],['zone_08','古魯丁地監3樓'],['zone_09','古魯丁地監4樓'],['zone_10','古魯丁地監5樓'],['zone_11','古魯丁地監6樓'],['zone_12','古魯丁地監7樓'],['zone_13','說話之島地監1樓'],['zone_14','說話之島地監2樓'],['zone_15','眠龍洞穴1樓'],['zone_16','眠龍洞穴2樓'],['zone_17','眠龍洞穴3樓'],['zone_22','沙漠地監1樓'],['zone_23','沙漠地監2樓'],['zone_24','沙漠地監3樓'],['zone_25','沙漠地監4樓'],['zone_32','螞蟻洞窟1樓'],['zone_33','螞蟻洞窟2樓'],['zone_26','龍之谷地監1樓'],['zone_27','龍之谷地監2樓'],['zone_28','龍之谷地監3樓'],['zone_29','龍之谷地監4樓'],['zone_30','龍之谷地監5樓'],['zone_31','龍之谷地監6樓']]};
const ITEM_NAMES={potion_red:'紅色藥水',potion_orange:'橙色藥水',potion_clear:'白色藥水',wpn_5:'箭',wpn_22:'銀箭',scroll_weapon:'對武器施法的卷軸',scroll_armor:'對盔甲施法的卷軸',item_dagger:'匕首',item_sword:'長劍',item_bow:'獵人之弓',item_staff:'魔杖',item_leather_armor:'皮甲',item_chain_mail:'鎖子甲',item_helmet:'頭盔',item_shield:'盾牌',skillbook_light:'魔法書(光箭)',skillbook_heal:'魔法書(初級治癒術)'};
const ITEM_IMG={potion_red:'assets/icons/items/紅色藥水.png',potion_orange:'assets/icons/items/橙色藥水.png',potion_clear:'assets/icons/items/白色藥水.png',wpn_5:'assets/icons/weapons/箭.png',wpn_22:'assets/icons/weapons/銀箭.png',scroll_weapon:'assets/icons/items/對武器施法的卷軸.png',scroll_armor:'assets/icons/items/對盔甲施法的卷軸.png',item_dagger:'assets/icons/weapons/匕首.png',item_sword:'assets/icons/weapons/長劍.png',item_bow:'assets/icons/weapons/獵人之弓.png',item_staff:'assets/icons/weapons/魔杖.png',item_leather_armor:'assets/icons/armors/皮甲.png',item_chain_mail:'assets/icons/armors/鎖子甲.png',item_helmet:'assets/icons/armors/頭盔.png',item_shield:'assets/icons/armors/盾牌.png',skillbook_light:'assets/icons/items/魔法書(光箭).png',skillbook_heal:'assets/icons/items/魔法書(初級治癒術).png'};
const SKILL_NAMES={sk_light_arrow:'光箭',sk_heal:'初級治癒術'};
const MOB_NAMES={orc:'妖魔',goblin:'哥布林',orc_archer:'妖魔弓箭手',gremlin:'格利芬',zombie:'殭屍',wolf:'狼',skeleton:'骷髏',fighter:'妖魔鬥士',stone_golem:'石頭高崙',spider:'蜘蛛',ghoul:'食屍鬼',sparto:'史巴托',lycan:'狼人',gaster:'卡司特',orc_mage:'妖魔法師',hobgoblin:'哈柏哥布林',bear:'熊',lizardman:'蜥蜴人',ant:'螞蟻',giant_ant:'巨大螞蟻',scorpion:'蠍子',evil_lizard:'邪惡蜥蜴',skel_archer:'骷髏弓箭手',skel_spear:'骷髏槍兵',skel_axe:'骷髏斧兵',ogre:'歐吉',cerberus:'地獄犬',elder:'長者',necromancer:'死靈法師',dk:'死亡騎士',black_knight:'黑騎士',b_knight:'黑騎士',kurt:'克特',dark_elf:'黑暗妖精',ogre_warrior:'歐吉戰士',arian:'亞力安',wyvern:'飛龍',blackelder:'黑長者',dragon:'巨龍',ant_queen:'巨大蟻后'};
const EQUIP_PARTS=[['helm','頭部'],['cloak','披風'],['amulet','項鍊'],['wpn','武器'],['armor','盔甲'],['shield','盾牌'],['gloves','手套'],['boots','鞋子'],['ring','戒指']];
const INVENTORY_SLOTS=36;
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(a,b){return b>0?Math.max(0,Math.min(100,a/b*100)):0}
function img(path,cls){return `<img class="${cls||''}" src="${encodeURI(path)}" onerror="this.style.display='none'" draggable="false">`}
function mobImg(id){return `assets/anim/${MOB_NAMES[id]||id}/attack_0.png`}
function areaBg(map){if(map==='dragon_valley')return'assets/area/1920x1080/龍之谷.jpg';if(/^zone_(26|27|28)$/.test(map))return'assets/area/1920x1080/地監.jpg';if(/^zone_(29|30|31)$/.test(map))return'assets/area/1920x1080/地監深層.jpg';if(/^zone_(06|07|08)$/.test(map))return`assets/area/1920x1080/古魯丁地監${Number(map.slice(5))-5}樓.jpg`;if(/^zone_(09|10|11|12)$/.test(map))return'assets/area/1920x1080/地監深層.jpg';if(/^zone_/.test(map))return'assets/area/1920x1080/地監.jpg';if(map==='desert'||map==='windwood')return'assets/area/1920x1080/沙漠.jpg';if(map==='elf_forest'||map==='zone_01')return'assets/area/1920x1080/森林.jpg';if(map==='gludio')return'assets/area/1920x1080/古魯丁.jpg';return'assets/area/1920x1080/城鎮周邊.jpg'}
function showGame(){$('creation-screen')?.classList.add('hidden');$('game-screen')?.classList.remove('hidden')}
function showCreate(){$('creation-screen')?.classList.remove('hidden');$('game-screen')?.classList.add('hidden')}
function ensurePortrait(){let p=$('char-portrait');if(p)return p;let status=$('char-name')?.closest('.status');if(!status)return null;p=document.createElement('img');p.id='char-portrait';p.style.cssText='width:100%;height:150px;object-fit:contain;object-position:center bottom;margin:-6px 0 6px;filter:drop-shadow(0 5px 8px #000);';status.insertBefore(p,status.firstChild);return p}
function renderCharacter(c){if(!c)return;showGame();let portrait=ensurePortrait();if(portrait)portrait.src=CLASS_IMG[c.cls]||'';$('char-name').textContent=c.name||'';$('char-class').textContent=CLASS_NAMES[c.cls]||c.cls||'';$('char-level').textContent=c.lv||1;$('char-gold').textContent=Number(c.gold||0).toLocaleString();$('hp-text').textContent=`${c.hp||0}/${c.maxHp||0}`;$('mp-text').textContent=`${c.mp||0}/${c.maxMp||0}`;$('hp-fill').style.width=pct(c.hp,c.maxHp)+'%';$('mp-fill').style.width=pct(c.mp,c.maxMp)+'%';$('exp-text').textContent=`${c.exp||0}/${c.expNeed||0}`;$('exp-fill').style.width=pct(c.exp,c.expNeed)+'%';const s=c.stats||{};for(const k of ['str','dex','con','int','wis','cha'])if($('stat-'+k))$('stat-'+k).textContent=s[k]??'-';$('stat-atk').textContent=c.atk??'-';$('stat-ac').textContent=c.ac??'-';$('stat-sp').textContent=c.sp??'-';renderInventory(c);renderEquipment(c);renderSkills(c);syncMap(c.map)}
function itemDetail(i){const name=(ITEM_NAMES[i.id]||i.id)+(i.en?` +${i.en}`:'');return `<b>${esc(name)}</b><span>數量：${Number(i.cnt)||1}${i.bless?'　祝福':''}</span><br><span>${/^potion_/.test(i.id)?'點擊使用藥水':/^skillbook_/.test(i.id)?'點擊學習魔法':/^item_/.test(i.id)?'點擊裝備此物品':'伺服器管理物品'}</span>`}
function showItemDetail(uid,on){const tip=$('inventory-tooltip'),snap=window.MMO149Realtime?.snapshot()?.self,it=snap?.inventory?.find(x=>x.uid===uid);if(!tip||!it)return;if(on){tip.innerHTML=itemDetail(it);tip.classList.add('visible')}else tip.classList.remove('visible')}
function inventoryTap(e,uid){if(window.matchMedia('(hover: hover)').matches)return itemAction(uid);const el=e.currentTarget;if(!el.classList.contains('selected')){document.querySelectorAll('.inventory-slot.selected').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');showItemDetail(uid,true);return}itemAction(uid)}
function renderInventory(c){let box=$('inventory-list');if(!box)return;let rows=c.inventory||[],slots=[];for(let n=0;n<INVENTORY_SLOTS;n++){const i=rows[n];slots.push(i?`<button class="inventory-slot" aria-label="${esc(ITEM_NAMES[i.id]||i.id)}" onmouseenter="ThinUI.itemDetail('${esc(i.uid)}',true)" onmouseleave="ThinUI.itemDetail('${esc(i.uid)}',false)" onclick="ThinUI.inventoryTap(event,'${esc(i.uid)}')">${img(ITEM_IMG[i.id]||'assets/favicon.png','item-icon')}${i.en?`<span class="item-enhance">+${i.en}</span>`:''}<span class="item-count">${Number(i.cnt)||1}</span></button>`:`<div class="inventory-slot empty-slot"></div>`)}box.innerHTML=`<div class="inventory-header"><span>背包</span><span>${rows.length} / ${INVENTORY_SLOTS}</span></div><div class="inventory-grid">${slots.join('')}</div><div class="inventory-hint">滑鼠移入查看詳情；手機點一下查看、再點一下使用／裝備</div>`}
function equipItemForSlot(c,slot){const eq=c.equipment||{},uid=eq[slot]||eq[slot==='wpn'?'weapon':slot==='helm'?'helmet':slot]||'';return(c.inventory||[]).find(i=>i.uid===uid)||null}
function renderEquipment(c){let box=$('equipment-list');if(!box)return;let slots=EQUIP_PARTS.map(([slot,label])=>{let i=equipItemForSlot(c,slot);return `<button class="equip-slot ${i?'filled':''}" data-equip-pos="${slot}" ${i?`onclick="ThinUI.unequip('${esc(slot)}')" title="點擊卸下 ${(ITEM_NAMES[i.id]||i.id)}"`:''}>${i?`${img(ITEM_IMG[i.id]||'assets/favicon.png','equip-icon')}<small>${esc((ITEM_NAMES[i.id]||i.id)+(i.en?` +${i.en}`:''))}</small>`:`<span class="part-label">${label}</span>`}</button>`}).join('');box.innerHTML=`<div class="equipment-board"><div class="equipment-silhouette"></div>${slots}<div class="equipment-note">點擊已裝備的圖示即可卸下</div></div>`}
function renderSkills(c){let box=$('skill-list');if(!box)return;box.innerHTML=(c.skills||[]).length?(c.skills||[]).map(s=>`<div class="skill-row">${esc(SKILL_NAMES[s]||s)}</div>`).join(''):'<div class="empty">尚未習得技能</div>'}
function renderWorld(w){if(!w)return;$('map-name').textContent=w.name||w.map;let world=document.querySelector('.world');if(world){world.style.backgroundImage=`linear-gradient(rgba(4,10,18,.28),rgba(4,10,18,.55)),url("${encodeURI(areaBg(w.map))}")`;world.style.backgroundSize='cover';world.style.backgroundPosition='center'}let box=$('mob-list');if(!box)return;box.innerHTML=(w.mobs||[]).map(m=>`<button class="mob-card ${m.dead?'dead':''}" ${m.dead?'disabled':''} onclick="ThinUI.attack('${esc(m.uid)}')">${img(mobImg(m.templateId),'mob-sprite')}<strong>${esc(MOB_NAMES[m.templateId]||m.templateId)}</strong><span>Lv.${m.lv}</span><div class="mini-bar"><i style="width:${pct(m.hp,m.maxHp)}%"></i></div><small>${m.hp}/${m.maxHp}</small><em>${m.dead?'等待重生':'點擊攻擊'}</em></button>`).join('')}
function renderPresence(players){players=players||[];$('online-count').textContent=players.length;if($('player-tab-count'))$('player-tab-count').textContent=players.length;let box=$('online-list');if(box)box.innerHTML=players.length?players.map(p=>`<div class="player-entry">${img(CLASS_IMG[p.cls]||'assets/favicon.png','player-avatar')}<div><b>${esc(p.name)}</b><small>${esc(CLASS_NAMES[p.cls]||p.cls||'冒險者')}</small></div><span class="player-level">Lv.${p.lv||1}</span></div>`).join(''):'<div class="empty">目前沒有其他在線玩家</div>'}
function appendChat(p){let box=$('world-log');if(!box)return;let d=document.createElement('div');d.innerHTML=`<b>[${esc(p.name||'玩家')}]</b> ${esc(p.text||'')}`;box.appendChild(d);box.scrollTop=box.scrollHeight}
function appendEvent(evt){if(!evt)return;let box=$('combat-log');if(!box)return;let msg='';if(evt.type==='attack')msg=evt.hit?`造成 ${evt.dmg} 點傷害${evt.kill?`，擊倒目標，獲得 ${evt.exp} EXP / ${evt.gold} 金幣`:''}`:'攻擊未命中';else if(evt.type==='buy')msg=`購買 ${ITEM_NAMES[evt.id]||evt.id} x${evt.qty}`;else if(evt.type==='sell')msg=`販賣 ${ITEM_NAMES[evt.id]||evt.id} x${evt.qty}，獲得 ${evt.gain} 金幣`;else if(evt.type==='use_item')msg=`使用 ${ITEM_NAMES[evt.id]||evt.id}${evt.heal?`，恢復 ${evt.heal} HP`:''}`;else if(evt.type==='map_change')msg=`移動到 ${evt.to}`;else if(evt.type==='revive')msg='角色已復活';if(msg){let d=document.createElement('div');d.textContent=msg;box.appendChild(d);box.scrollTop=box.scrollHeight}}
function connection(on,authed){let e=$('connection-state');if(e){e.textContent=on?(authed?'已連線 / Server Authority':'已連線 / 驗證中'):'離線';e.className=on?'online':'offline'}}
function fillMaps(group){let sel=$('map-select');if(sel)sel.innerHTML=(MAP_GROUPS[group]||[]).map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}
function syncMap(map){for(const[g,rows]of Object.entries(MAP_GROUPS))if(rows.some(x=>x[0]===map)){if($('map-category').value!==g){$('map-category').value=g;fillMaps(g)}$('map-select').value=map;break}}
function setupCreation(){document.querySelectorAll('[data-class]').forEach(b=>{let cls=b.dataset.class;b.innerHTML=`${img(CLASS_IMG[cls],'create-class-img')}<span>${CLASS_NAMES[cls]}</span>`;b.onclick=()=>{document.querySelectorAll('[data-class]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('create-class').value=cls}});$('roll-button').onclick=()=>window.MMO149Realtime?.rollStats();$('create-button').onclick=()=>{let name=$('create-name').value.trim(),cls=$('create-class').value,rollId=$('roll-id').value;if(name.length<2)return alert('角色名稱至少 2 個字。');if(!cls)return alert('請選擇職業。');if(!rollId)return alert('請先擲骰。');window.MMO149Realtime?.createCharacter(name,cls,rollId)}}
function showRoll(p){if(!p)return;$('roll-id').value=p.rollId||'';let s=p.stats||{};for(const k of ['str','dex','con','int','wis','cha'])$('roll-'+k).textContent=s[k]??'-'}
function switchTab(tab){document.querySelectorAll('.client-tab').forEach(x=>x.classList.add('hidden'));$('tab-'+tab)?.classList.remove('hidden');document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab))}
function itemAction(uid){let snap=window.MMO149Realtime?.snapshot()?.self,it=snap?.inventory?.find(i=>i.uid===uid);if(!it)return;if(/^potion_|^skillbook_/.test(it.id))return window.MMO149Realtime.useItem(uid);if(/^item_/.test(it.id))return window.MMO149Realtime.equip(uid);alert('此物品目前由伺服器管理，尚無可用操作。')}
function sendChat(){let i=$('world-input'),t=i.value.trim();if(t){window.MMO149Realtime?.chat(t);i.value=''}}
function injectStyles(){let s=document.createElement('style');s.textContent='.mob-sprite{width:96px;height:96px;object-fit:contain;image-rendering:auto;filter:drop-shadow(0 5px 7px #000)}.create-class-img{width:82px;height:82px;object-fit:contain;display:block;margin:0 auto 6px;filter:drop-shadow(0 5px 7px #000)}.class-btn{min-height:132px}.world{transition:background-image .18s ease}.mob-card{backdrop-filter:blur(2px)}';document.head.appendChild(s)}
function init(){document.title='放置天堂 - 1.49 即時世界';injectStyles();fillMaps('village');$('map-category').onchange=e=>fillMaps(e.target.value);$('map-go').onclick=()=>{let v=$('map-select').value;if(v)window.MMO149Realtime?.changeMap(v)};$('world-send').onclick=sendChat;$('world-input').onkeydown=e=>{if(e.key==='Enter')sendChat()};setupCreation();switchTab('items')}
window.player={name:'',cls:null};window.mapState={current:'town_talking',mobs:[]};
window.ThinUI={init,renderCharacter,renderWorld,renderPresence,appendChat,appendEvent,connection,showCreate,showRoll,switchTab,itemAction,itemDetail:showItemDetail,inventoryTap,attack:uid=>window.MMO149Realtime?.attack(uid),unequip:slot=>window.MMO149Realtime?.unequip(slot)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
