// MMO2 1.49 thin client UI. No game authority lives here.
(function(){
'use strict';
const CLASS_NAMES={royal:'王族',knight:'騎士',mage:'法師',elf:'妖精'};
const MAP_GROUPS={
  village:[['town_talking','說話之島'],['town_silver_knight','銀騎士村'],['town_elf','妖精森林'],['town_gludio','燃柳村'],['town_gludin','古魯丁村莊']],
  wild:[['training','新兵修練場'],['talking_island','說話之島周邊'],['talking_island_port','說話之島港口'],['silver_knight','銀騎士地區'],['zone_01','妖精森林周邊'],['elf_forest','妖魔森林'],['gludio','古魯丁'],['windwood','風木'],['desert','沙漠'],['kent','肯特'],['dragon_valley','龍之谷']],
  dungeon:[['zone_06','古魯丁地監1樓'],['zone_07','古魯丁地監2樓'],['zone_08','古魯丁地監3樓'],['zone_09','古魯丁地監4樓'],['zone_10','古魯丁地監5樓'],['zone_11','古魯丁地監6樓'],['zone_12','古魯丁地監7樓'],['zone_13','說話之島地監1樓'],['zone_14','說話之島地監2樓'],['zone_15','眠龍洞穴1樓'],['zone_16','眠龍洞穴2樓'],['zone_17','眠龍洞穴3樓'],['zone_22','沙漠地監1樓'],['zone_23','沙漠地監2樓'],['zone_24','沙漠地監3樓'],['zone_25','沙漠地監4樓'],['zone_32','螞蟻洞窟1樓'],['zone_33','螞蟻洞窟2樓'],['zone_26','龍之谷地監1樓'],['zone_27','龍之谷地監2樓'],['zone_28','龍之谷地監3樓'],['zone_29','龍之谷地監4樓'],['zone_30','龍之谷地監5樓'],['zone_31','龍之谷地監6樓']],
  special:[]
};
const ITEM_NAMES={potion_red:'紅色藥水',potion_orange:'橙色藥水',potion_clear:'白色藥水',wpn_5:'箭',wpn_22:'銀箭',scroll_weapon:'對武器施法的卷軸',scroll_armor:'對盔甲施法的卷軸',item_dagger:'匕首',item_sword:'長劍',item_bow:'獵人之弓',item_staff:'魔杖',item_leather_armor:'皮甲',item_chain_mail:'鎖子甲',item_helmet:'頭盔',item_shield:'盾牌',skillbook_light:'魔法書(光箭)',skillbook_heal:'魔法書(初級治癒術)'};
const SKILL_NAMES={sk_light_arrow:'光箭',sk_heal:'初級治癒術'};
const MOB_NAMES={orc:'妖魔',goblin:'哥布林',orc_archer:'妖魔弓箭手',gremlin:'格利芬',zombie:'殭屍',wolf:'狼',skeleton:'骷髏',fighter:'妖魔鬥士',stone_golem:'石頭高崙',spider:'蜘蛛',ghoul:'食屍鬼',sparto:'史巴托',lycan:'狼人',gaster:'卡司特',orc_mage:'妖魔法師',hobgoblin:'哈柏哥布林',bear:'熊',lizardman:'蜥蜴人',ant:'螞蟻',giant_ant:'巨大螞蟻',scorpion:'蠍子',evil_lizard:'邪惡蜥蜴',skel_archer:'骷髏弓箭手',skel_spear:'骷髏槍兵',skel_axe:'骷髏斧兵',ogre:'歐吉',cerberus:'地獄犬',elder:'長者',necromancer:'死靈法師',dk:'死亡騎士',black_knight:'黑騎士',b_knight:'黑騎士',kurt:'克特',dark_elf:'黑暗妖精',ogre_warrior:'歐吉戰士',arian:'亞力安',wyvern:'飛龍',blackelder:'黑長者',dragon:'巨龍',ant_queen:'巨大蟻后'};
let currentTab='items';
function $(id){return document.getElementById(id);}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function pct(a,b){return b>0?Math.max(0,Math.min(100,a/b*100)):0;}
function showGame(){ $('creation-screen')?.classList.add('hidden'); $('game-screen')?.classList.remove('hidden'); }
function showCreate(){ $('creation-screen')?.classList.remove('hidden'); $('game-screen')?.classList.add('hidden'); }
function renderCharacter(c){if(!c)return;showGame();$('char-name').textContent=c.name||'';$('char-class').textContent=CLASS_NAMES[c.cls]||c.cls||'';$('char-level').textContent=c.lv||1;$('char-gold').textContent=Number(c.gold||0).toLocaleString();$('hp-text').textContent=`${c.hp||0}/${c.maxHp||0}`;$('mp-text').textContent=`${c.mp||0}/${c.maxMp||0}`;$('hp-fill').style.width=pct(c.hp,c.maxHp)+'%';$('mp-fill').style.width=pct(c.mp,c.maxMp)+'%';$('exp-text').textContent=`${c.exp||0}/${c.expNeed||0}`;$('exp-fill').style.width=pct(c.exp,c.expNeed)+'%';const s=c.stats||{};for(const k of ['str','dex','con','int','wis','cha']){let e=$('stat-'+k);if(e)e.textContent=s[k]??'-';}$('stat-atk').textContent=c.atk??'-';$('stat-ac').textContent=c.ac??'-';$('stat-sp').textContent=c.sp??'-';renderInventory(c);renderEquipment(c);renderSkills(c);syncMap(c.map);}
function renderInventory(c){let box=$('inventory-list');if(!box)return;let rows=(c.inventory||[]);box.innerHTML=rows.length?rows.map(i=>`<button class="item-row" onclick="ThinUI.itemAction('${esc(i.uid)}')"><span>${esc(ITEM_NAMES[i.id]||i.id)}${i.en?` +${i.en}`:''}</span><b>x${i.cnt||1}</b></button>`).join(''):'<div class="empty">背包是空的</div>';}
function renderEquipment(c){let box=$('equipment-list');if(!box)return;const byUid=new Map((c.inventory||[]).map(i=>[i.uid,i]));box.innerHTML=Object.entries(c.equipment||{}).map(([slot,u])=>{let i=byUid.get(u),n=i?(ITEM_NAMES[i.id]||i.id):'未裝備';return `<button class="equip-row" onclick="ThinUI.unequip('${esc(slot)}')"><span>${esc(slot.toUpperCase())}</span><b>${esc(n)}</b></button>`;}).join('');}
function renderSkills(c){let box=$('skill-list');if(!box)return;box.innerHTML=(c.skills||[]).length?(c.skills||[]).map(s=>`<div class="skill-row">${esc(SKILL_NAMES[s]||s)}</div>`).join(''):'<div class="empty">尚未習得技能</div>';}
function renderWorld(w){if(!w)return;$('map-name').textContent=w.name||w.map;let box=$('mob-list');if(!box)return;box.innerHTML=(w.mobs||[]).map(m=>`<button class="mob-card ${m.dead?'dead':''}" ${m.dead?'disabled':''} onclick="ThinUI.attack('${esc(m.uid)}')"><strong>${esc(MOB_NAMES[m.templateId]||m.templateId)}</strong><span>Lv.${m.lv}</span><div class="mini-bar"><i style="width:${pct(m.hp,m.maxHp)}%"></i></div><small>${m.hp}/${m.maxHp}</small><em>${m.dead?'等待重生':'點擊攻擊'}</em></button>`).join('');}
function renderPresence(players){$('online-count').textContent=(players||[]).length;let box=$('online-list');if(box)box.innerHTML=(players||[]).map(p=>`<div><b>${esc(p.name)}</b> Lv.${p.lv} · ${esc(CLASS_NAMES[p.cls]||p.cls)}</div>`).join('');}
function appendChat(p){let box=$('world-log');if(!box)return;let d=document.createElement('div');d.innerHTML=`<b>[${esc(p.name||'玩家')}]</b> ${esc(p.text||'')}`;box.appendChild(d);box.scrollTop=box.scrollHeight;}
function appendEvent(evt){if(!evt)return;let box=$('combat-log');if(!box)return;let msg='';if(evt.type==='attack')msg=evt.hit?`造成 ${evt.dmg} 點傷害${evt.kill?`，擊倒目標，獲得 ${evt.exp} EXP / ${evt.gold} 金幣`:''}`:'攻擊未命中';else if(evt.type==='buy')msg=`購買 ${ITEM_NAMES[evt.id]||evt.id} x${evt.qty}`;else if(evt.type==='sell')msg=`販賣 ${ITEM_NAMES[evt.id]||evt.id} x${evt.qty}，獲得 ${evt.gain} 金幣`;else if(evt.type==='use_item')msg=`使用 ${ITEM_NAMES[evt.id]||evt.id}${evt.heal?`，恢復 ${evt.heal} HP`:''}`;else if(evt.type==='map_change')msg=`移動到 ${MAP_GROUPS.village.concat(MAP_GROUPS.wild,MAP_GROUPS.dungeon).find(x=>x[0]===evt.to)?.[1]||evt.to}`;else if(evt.type==='revive')msg='角色已復活';if(!msg)return;let d=document.createElement('div');d.textContent=msg;box.appendChild(d);box.scrollTop=box.scrollHeight;}
function connection(on,authed){let e=$('connection-state');if(e){e.textContent=on?(authed?'已連線 / Server Authority':'已連線 / 驗證中'):'離線';e.className=on?'online':'offline';}}
function fillMaps(group){let sel=$('map-select');if(!sel)return;sel.innerHTML=(MAP_GROUPS[group]||[]).map(([v,n])=>`<option value="${v}">${n}</option>`).join('');}
function syncMap(map){for(const [g,rows] of Object.entries(MAP_GROUPS)){if(rows.some(x=>x[0]===map)){if($('map-category').value!==g){$('map-category').value=g;fillMaps(g);}$('map-select').value=map;break;}}}
function setupCreation(){document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-class]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('create-class').value=b.dataset.class;});$('roll-button').onclick=()=>window.MMO149Realtime?.rollStats();$('create-button').onclick=()=>{let name=$('create-name').value.trim(),cls=$('create-class').value,rollId=$('roll-id').value;if(name.length<2)return alert('角色名稱至少 2 個字。');if(!cls)return alert('請選擇職業。');if(!rollId)return alert('請先擲骰。');window.MMO149Realtime?.createCharacter(name,cls,rollId);};}
function showRoll(p){if(!p)return;$('roll-id').value=p.rollId||'';let s=p.stats||{};for(const k of ['str','dex','con','int','wis','cha'])$('roll-'+k).textContent=s[k]??'-';}
function switchTab(tab){currentTab=tab;document.querySelectorAll('.client-tab').forEach(x=>x.classList.add('hidden'));$('tab-'+tab)?.classList.remove('hidden');document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));}
function itemAction(uid){let snap=window.MMO149Realtime?.snapshot()?.self,it=snap?.inventory?.find(i=>i.uid===uid);if(!it)return;let id=it.id;if(/^potion_|^skillbook_/.test(id)){window.MMO149Realtime.useItem(uid);return;}if(/^item_/.test(id)){window.MMO149Realtime.equip(uid);return;}alert('此物品目前由伺服器管理，尚無可用操作。');}
function init(){document.title='放置天堂 - 1.49 即時世界';$('login-disclaimer')?.remove();document.querySelectorAll('.legacy-only').forEach(x=>x.remove());fillMaps('village');$('map-category').onchange=e=>fillMaps(e.target.value);$('map-go').onclick=()=>{let v=$('map-select').value;if(v)window.MMO149Realtime?.changeMap(v);};$('world-send').onclick=sendChat;$('world-input').onkeydown=e=>{if(e.key==='Enter')sendChat();};setupCreation();switchTab('items');}
function sendChat(){let i=$('world-input'),t=i.value.trim();if(t){window.MMO149Realtime?.chat(t);i.value='';}}
window.player={name:'',cls:null};window.mapState={current:'town_talking',mobs:[]};
window.ThinUI={init,renderCharacter,renderWorld,renderPresence,appendChat,appendEvent,connection,showCreate,showRoll,switchTab,itemAction,attack:uid=>window.MMO149Realtime?.attack(uid),unequip:slot=>window.MMO149Realtime?.unequip(slot)};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
