// MMO2 player marketplace UI. Supports both static and legacy injected HUD markup.
(function(){
'use strict';
const N={potion_red:'紅色藥水',potion_orange:'橙色藥水',potion_clear:'白色藥水',wpn_5:'箭',wpn_22:'銀箭',scroll_weapon:'對武器施法的卷軸',scroll_armor:'對盔甲施法的卷軸',item_dagger:'匕首',item_sword:'長劍',item_bow:'獵人之弓',item_staff:'魔杖',item_leather_armor:'皮甲',item_chain_mail:'鎖子甲',item_helmet:'頭盔',item_shield:'盾牌',skillbook_light:'魔法書(光箭)',skillbook_heal:'魔法書(初級治癒術)'};
let listings=[];const $=id=>document.getElementById(id),esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setup(){const right=document.querySelector('.side.right'),tabs=right?.querySelector(':scope > .tabs'),host=$('right-content-panel')||right?.querySelector(':scope > .panel:nth-child(2)');if(!tabs||!host)return false;if($('tab-market')){injectStyle();return true;}const b=document.createElement('button');b.className='btn';b.dataset.tab='market';b.textContent='交易所';b.onclick=()=>open();tabs.appendChild(b);const p=document.createElement('div');p.id='tab-market';p.className='client-tab hidden';p.innerHTML='<div class="market-head"><button class="btn market-mode active" data-mode="browse">市場</button><button class="btn market-mode" data-mode="mine">我的上架</button><button class="btn market-mode" data-mode="sell">背包上架</button><button class="btn" id="market-refresh">刷新</button></div><div id="market-body"></div>';host.appendChild(p);bindStatic();injectStyle();return true;}
function bindStatic(){document.querySelectorAll('#tab-market .market-mode').forEach(x=>x.onclick=()=>mode(x.dataset.mode));const r=$('market-refresh');if(r)r.onclick=()=>window.MMO149Realtime?.marketList?.();}
function injectStyle(){if($('market-ui-style'))return;const s=document.createElement('style');s.id='market-ui-style';s.textContent='.market-card{border:1px solid #334155;background:#0b1624;border-radius:7px;padding:9px;margin-bottom:7px}.market-card-top{display:flex;justify-content:space-between;gap:8px}.market-name{font-weight:700;color:#fde68a}.market-price{color:#86efac;font-weight:700}.market-meta{font-size:12px;color:#94a3b8;margin:4px 0 7px}.market-card .btn{width:100%;padding:7px}.market-sell-row{display:grid;grid-template-columns:1fr 62px 90px;gap:5px;align-items:center}.market-sell-row input{min-width:0;width:100%;padding:7px;background:#0f172a;border:1px solid #475569;color:#fff;border-radius:5px}.market-empty{padding:25px 8px;text-align:center;color:#64748b}.market-gold{margin-bottom:8px;color:#facc15;font-weight:700}';document.head.appendChild(s);}
function switchBase(){document.querySelectorAll('.side.right .client-tab').forEach(x=>x.classList.add('hidden'));$('tab-market')?.classList.remove('hidden');document.querySelectorAll('.side.right .tabs .btn').forEach(x=>x.classList.toggle('active',x.dataset.tab==='market'));}
function open(){setup();switchBase();mode('browse');window.MMO149Realtime?.marketList?.();}
function mode(m){if(!setup())return;switchBase();$('tab-market').dataset.mode=m;document.querySelectorAll('.market-mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));draw();}
function render(rows){listings=Array.isArray(rows)?rows:[];setup();draw();}
function draw(){const body=$('market-body');if(!body)return;const m=$('tab-market')?.dataset.mode||'browse',self=window.MMO149Realtime?.snapshot?.()?.self;if(m==='sell')return drawSell(body,self);const rows=m==='mine'?listings.filter(x=>x.mine):listings.filter(x=>!x.mine);body.innerHTML='<div class="market-gold">持有金幣：'+Number(self?.gold||0).toLocaleString()+'</div>'+(rows.length?rows.map(x=>`<div class="market-card"><div class="market-card-top"><span class="market-name">${esc(x.itemName||N[x.itemId]||x.itemId)}${x.en?` +${Number(x.en)}`:''} × ${Number(x.qty)||1}</span><span class="market-price">${Number(x.price||0).toLocaleString()} 金幣</span></div><div class="market-meta">賣家：${esc(x.sellerName||'玩家')}</div>${x.mine?`<button class="btn" onclick="MMO149MarketUI.cancel('${esc(x.id)}')">取消上架</button>`:`<button class="btn" onclick="MMO149MarketUI.buy('${esc(x.id)}',${Number(x.price)||0})">購買</button>`}</div>`).join(''):'<div class="market-empty">目前沒有商品</div>');}
function equipped(self,uid){return Object.values(self?.equipment||{}).includes(uid)}function drawSell(body,self){const rows=(self?.inventory||[]).filter(i=>!equipped(self,i.uid)&&!i.lock);body.innerHTML='<div class="market-gold">選擇背包物品並設定「數量 / 總售價」</div>'+(rows.length?rows.map(i=>`<div class="market-card"><div class="market-name">${esc(N[i.id]||i.id)}${i.en?` +${Number(i.en)}`:''}　持有 ${Number(i.cnt)||1}</div><div class="market-sell-row"><span></span><input id="mq-${esc(i.uid)}" type="number" min="1" max="${Number(i.cnt)||1}" value="1"><input id="mp-${esc(i.uid)}" type="number" min="1" value="100"></div><button class="btn" onclick="MMO149MarketUI.sell('${esc(i.uid)}')">上架</button></div>`).join(''):'<div class="market-empty">沒有可上架的物品</div>');}
function sell(uid){const q=Math.max(1,Math.floor(Number($('mq-'+uid)?.value)||1)),p=Math.max(1,Math.floor(Number($('mp-'+uid)?.value)||0));if(confirm(`確定以 ${p.toLocaleString()} 金幣上架此商品？`)){window.MMO149Realtime?.marketSell?.(uid,q,p);setTimeout(()=>window.MMO149Realtime?.marketList?.(),250)}}function buy(id,price){if(confirm(`確定花費 ${Number(price).toLocaleString()} 金幣購買？`))window.MMO149Realtime?.marketBuy?.(id)}function cancel(id){if(confirm('確定取消上架並取回物品？'))window.MMO149Realtime?.marketCancel?.(id)}function refreshInventory(){if($('tab-market')?.dataset.mode==='sell'&&!$('tab-market').classList.contains('hidden'))draw()}
function boot(){if(!setup()){const t=setInterval(()=>{if(setup())clearInterval(t)},50)}else bindStatic()}
window.MMO149MarketUI={render,open,mode,sell,buy,cancel,refreshInventory};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();