// GM POS + World Boss UI. Load before 33-realtime.js so it can observe server packets.
(function(){'use strict';
let gm=false,menu=[],boss=null;
const NativeWebSocket=window.WebSocket;
class BossAwareWebSocket extends NativeWebSocket{constructor(...args){super(...args);this.addEventListener('message',e=>{try{const m=JSON.parse(e.data),p=m.payload||{};if(m.type==='gm_status')window.MMO149BossUI?.status?.(p);else if(m.type==='world_boss')window.MMO149BossUI?.update?.(p);else if(m.type==='snapshot'&&p.world?.boss)window.MMO149BossUI?.update?.({active:true,boss:p.world.boss});else if(m.type==='snapshot'&&p.event?.type==='world_boss_defeated')window.MMO149BossUI?.update?.({active:false,defeated:{name:p.event.name,killer:p.event.killer,rewards:p.event.rewards}});}catch(_){}});}}
window.WebSocket=BossAwareWebSocket;window.WebSocket.CONNECTING=NativeWebSocket.CONNECTING;window.WebSocket.OPEN=NativeWebSocket.OPEN;window.WebSocket.CLOSING=NativeWebSocket.CLOSING;window.WebSocket.CLOSED=NativeWebSocket.CLOSED;
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensure(){if(document.getElementById('gm-pos-btn'))return;const d=document.createElement('div');d.id='gm-pos-root';d.innerHTML=`<button id="gm-pos-btn" class="gm-pos-btn" type="button">GM POS</button><div id="gm-pos-modal" class="gm-pos-modal hidden"><div class="gm-pos-card"><div class="gm-pos-head"><div><b>滋味亭 POS</b><small>世界 BOSS 製造系統</small></div><button id="gm-pos-close">×</button></div><div id="gm-pos-menu"></div><div class="gm-pos-foot"><button id="gm-boss-cancel" class="btn">結束目前 BOSS</button></div></div></div><div id="world-boss-banner" class="world-boss-banner hidden"></div>`;document.body.appendChild(d);document.getElementById('gm-pos-btn').onclick=()=>document.getElementById('gm-pos-modal').classList.remove('hidden');document.getElementById('gm-pos-close').onclick=()=>document.getElementById('gm-pos-modal').classList.add('hidden');document.getElementById('gm-boss-cancel').onclick=()=>window.MMO149Realtime?.gmBossCancel?.();syncButton();}
function syncButton(){ensure();const live=gm||window.MMO149Realtime?.isGM?.()===true;const btn=document.getElementById('gm-pos-btn');if(!btn)return;btn.classList.remove('hidden');btn.style.cssText=live?'display:block!important;visibility:visible!important;opacity:1!important;position:fixed!important;right:18px!important;bottom:18px!important;z-index:2147483646!important;width:72px!important;height:72px!important;border:2px solid #e6b94c!important;border-radius:50%!important;background:#6f1d0b!important;color:#ffe79a!important;font-weight:900!important;cursor:pointer!important;box-shadow:0 0 20px #ffb02e!important':'display:none!important';}
function wireApi(){if(!window.MMO149Realtime)return setTimeout(wireApi,50);if(!window.MMO149Realtime.gmBossSpawn)window.MMO149Realtime.gmBossSpawn=menuId=>window.MMO149Realtime.send('gm_boss_spawn',{menuId});if(!window.MMO149Realtime.gmBossCancel)window.MMO149Realtime.gmBossCancel=()=>window.MMO149Realtime.send('gm_boss_cancel',{});syncButton();}
function renderMenu(){ensure();const box=document.getElementById('gm-pos-menu');if(!box)return;const groups={};for(const x of menu)(groups[x.category]||(groups[x.category]=[])).push(x);box.innerHTML=Object.entries(groups).map(([cat,rows])=>`<section class="pos-group"><h3>${esc(cat)}</h3><div class="pos-grid">${rows.map(x=>`<button class="pos-item" onclick="MMO149Realtime.gmBossSpawn('${esc(x.id)}')"><b>${esc(x.name)}</b><span>$${Number(x.price)||0}</span><small>製造 BOSS</small></button>`).join('')}</div></section>`).join('');}
function status(p){gm=!!p.gm;menu=Array.isArray(p.menu)?p.menu:menu;boss=p.boss||boss;syncButton();renderMenu();if(boss)update({active:true,boss});}
function update(p){ensure();const bar=document.getElementById('world-boss-banner');if(!p||!p.active){boss=null;bar.classList.add('hidden');if(p?.defeated)alert(`世界 BOSS「${p.defeated.name}」已被討伐！\n最後一擊：${p.defeated.killer||'冒險者'}`);return;}boss=p.boss||boss;if(!boss)return;bar.classList.remove('hidden');const hp=Math.max(0,Number(boss.hp)||0),max=Math.max(1,Number(boss.maxHp)||1),pc=Math.max(0,Math.min(100,hp/max*100));bar.innerHTML=`<div class="boss-title">⚔ 世界 BOSS　${esc(boss.name)} <small>${esc(boss.category||'')} / POS $${Number(boss.price)||0}</small></div><div class="boss-hp"><i style="width:${pc}%"></i><span>${hp.toLocaleString()} / ${max.toLocaleString()}</span></div><div class="boss-meta">GM：${esc(boss.spawnedBy||'GM')}　參戰 ${Number(boss.participants)||0} 人</div>`;}
window.MMO149BossUI={status,update,isGM:()=>gm,syncButton};ensure();wireApi();setInterval(syncButton,500);})();