// MMO2 GM POS + World Boss UI. Orders are server authoritative and shared by all GMs.
(function(){
'use strict';
let gm=false,menu=[],boss=null,cart={},orders=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensure(){const btn=document.getElementById('gm-pos-btn');if(!btn)return;btn.onclick=open;const modal=document.getElementById('gm-pos-modal');if(modal){const card=modal.querySelector('.gm-pos-card');if(card&&!document.getElementById('gm-pos-main'))card.innerHTML=`<div class="gm-pos-head"><div><b>滋味亭 POS</b><small>點餐 / 送單 / 共用訂單紀錄</small></div><button id="gm-pos-close" type="button">×</button></div><div id="gm-pos-main" class="pos-layout"><div><div class="pos-tabs"><button class="pos-tab active" data-pos-tab="menu">點餐</button><button class="pos-tab" data-pos-tab="history">以往訂單</button></div><div id="gm-pos-menu"></div><div id="gm-pos-history" class="hidden"></div></div><aside class="pos-cart"><h3>目前訂單</h3><div id="gm-pos-cart"></div><div class="pos-cart-total">合計 <b id="gm-pos-total">$0</b></div><div class="pos-cart-actions"><button id="gm-pos-clear" class="btn" type="button">清空</button><button id="gm-pos-submit" class="btn pos-submit" type="button">送出訂單</button></div><div class="pos-boss-tools"><button id="gm-boss-cancel" class="btn" type="button">結束目前 BOSS</button></div></aside></div>`;}document.getElementById('gm-pos-close')?.addEventListener('click',()=>modal?.classList.add('hidden'));document.getElementById('gm-pos-clear')?.addEventListener('click',()=>{cart={};renderCart()});document.getElementById('gm-pos-submit')?.addEventListener('click',submitOrder);document.getElementById('gm-boss-cancel')?.addEventListener('click',()=>window.MMO149Realtime?.gmBossCancel?.());document.querySelectorAll('[data-pos-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.posTab));syncButton()}
function isLiveGm(){return gm===true||window.MMO149Realtime?.isGM?.()===true}function syncButton(){const btn=document.getElementById('gm-pos-btn');if(btn)btn.style.display=isLiveGm()?'block':'none'}
function switchTab(tab){const m=document.getElementById('gm-pos-menu'),h=document.getElementById('gm-pos-history');document.querySelectorAll('[data-pos-tab]').forEach(b=>b.classList.toggle('active',b.dataset.posTab===tab));m?.classList.toggle('hidden',tab!=='menu');h?.classList.toggle('hidden',tab!=='history');if(tab==='history'){window.MMO149Realtime?.gmPosOrders?.();renderHistory()}}
function addItem(id){if(!menu.find(x=>x.id===id))return;cart[id]=(cart[id]||0)+1;renderCart()}function changeQty(id,d){if(!cart[id])return;cart[id]+=d;if(cart[id]<=0)delete cart[id];renderCart()}
function renderMenu(){ensure();const box=document.getElementById('gm-pos-menu');if(!box)return;if(!menu.length){box.innerHTML='<div class="pos-empty">POS 菜單尚未由伺服器送達。</div>';return}const groups={};for(const x of menu)(groups[x.category]||(groups[x.category]=[])).push(x);box.innerHTML=Object.entries(groups).map(([cat,rows])=>`<section class="pos-group"><h3>${esc(cat)}</h3><div class="pos-grid">${rows.map(x=>`<button class="pos-item" type="button" data-add-item="${esc(x.id)}"><b>${esc(x.name)}</b><span>$${Number(x.price)||0}</span><small>點一下加入訂單</small></button>`).join('')}</div></section>`).join('');box.querySelectorAll('[data-add-item]').forEach(b=>b.onclick=()=>addItem(b.dataset.addItem))}
function cartItems(){return Object.entries(cart).map(([id,qty])=>({id,qty:Number(qty)||0})).filter(x=>x.qty>0)}
function renderCart(){ensure();const box=document.getElementById('gm-pos-cart'),totalEl=document.getElementById('gm-pos-total');if(!box||!totalEl)return;let total=0;const rows=Object.entries(cart).map(([id,qty])=>{const x=menu.find(m=>m.id===id);if(!x)return'';const sub=(Number(x.price)||0)*qty;total+=sub;return `<div class="pos-cart-row"><div><b>${esc(x.name)}</b><small>$${Number(x.price)||0} × ${qty} = $${sub}</small></div><div class="pos-qty"><button data-qid="${esc(id)}" data-d="-1">−</button><span>${qty}</span><button data-qid="${esc(id)}" data-d="1">＋</button></div></div>`}).join('');box.innerHTML=rows||'<div class="pos-empty">尚未加入任何品項</div>';totalEl.textContent='$'+total;box.querySelectorAll('[data-qid]').forEach(b=>b.onclick=()=>changeQty(b.dataset.qid,Number(b.dataset.d)||0))}
function submitOrder(){const items=cartItems();if(!items.length){alert('目前訂單是空的。');return}if(!window.MMO149Realtime?.gmPosSubmit?.(items)){alert('伺服器尚未連線，訂單沒有送出。')}}
function setOrders(rows){orders=Array.isArray(rows)?rows:[];renderHistory()}
function orderCreated(order){if(order){orders=[order,...orders.filter(x=>x.id!==order.id)];cart={};renderCart();renderHistory();alert(`訂單已送出\n單號：${order.id}\n金額：$${Number(order.total)||0}\n世界 BOSS 已產生`)}}
function renderHistory(){ensure();const box=document.getElementById('gm-pos-history');if(!box)return;box.innerHTML=orders.length?`<div class="pos-history-list">${orders.map(o=>`<article class="pos-order"><header><b>${esc(o.id)}</b><span>${new Date(Number(o.createdAt||o.at)||Date.now()).toLocaleString('zh-TW')}</span></header><small>GM：${esc(o.createdBy||'GM')}　狀態：${esc(o.status||'')}</small><div>${(o.items||[]).map(x=>`<div class="pos-order-line"><span>${esc(x.name)} × ${Number(x.qty)||0}</span><b>$${(Number(x.price)||0)*(Number(x.qty)||0)}</b></div>`).join('')}</div><footer>合計 <b>$${Number(o.total)||0}</b>${o.killer?`　討伐：${esc(o.killer)}`:''}</footer></article>`).join('')}</div>`:'<div class="pos-empty">目前沒有伺服器訂單紀錄。</div>'}
function status(p){gm=!!p?.gm;if(Array.isArray(p?.menu)&&p.menu.length)menu=p.menu;if(Array.isArray(p?.orders))orders=p.orders;if(p?.boss)boss=p.boss;ensure();syncButton();renderMenu();renderCart();renderHistory();if(boss)update({active:true,boss})}
function update(p){ensure();const bar=document.getElementById('world-boss-banner');if(!bar)return;if(!p||!p.active){boss=null;bar.classList.add('hidden');if(p?.defeated)alert(`世界 BOSS「${p.defeated.name}」已被討伐！\n最後一擊：${p.defeated.killer||'冒險者'}`);if(isLiveGm())window.MMO149Realtime?.gmPosOrders?.();return}boss=p.boss||boss;if(!boss)return;bar.classList.remove('hidden');const hp=Math.max(0,Number(boss.hp)||0),max=Math.max(1,Number(boss.maxHp)||1),pc=Math.max(0,Math.min(100,hp/max*100));bar.innerHTML=`<div class="boss-title">⚔ 世界 BOSS　${esc(boss.name)} <small>${esc(boss.category||'POS訂單')} / POS $${Number(boss.price)||0}</small></div><div class="boss-hp"><i style="width:${pc}%"></i><span>${hp.toLocaleString()} / ${max.toLocaleString()}</span></div><div class="boss-meta">GM：${esc(boss.spawnedBy||'GM')}　參戰 ${Number(boss.participants)||0} 人</div>`}
function open(){ensure();renderMenu();renderCart();switchTab('menu');window.MMO149Realtime?.gmPosOrders?.();document.getElementById('gm-pos-modal')?.classList.remove('hidden')}
window.MMO149BossUI={status,update,setOrders,orderCreated,isGM:()=>isLiveGm(),syncButton,open,orders:()=>orders.slice()};function boot(){ensure();syncButton();setInterval(syncButton,500)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();