'use strict';
const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path'),{spawn}=require('child_process'),{Pool}=require('pg'),{WebSocketServer,WebSocket}=require('ws');
const PORT=Number(process.env.PORT||8080),HOST=process.env.HOST||'0.0.0.0',GAME_PORT=Number(process.env.GAME_PORT||PORT+1),DATABASE_URL=process.env.DATABASE_URL||'',MAX_MSG=16*1024,BACKEND_URL=`ws://127.0.0.1:${GAME_PORT}`;
if(!DATABASE_URL){console.error('DATABASE_URL is required for account authentication.');process.exit(1)}
const db=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:undefined});
const cleanAccount=v=>String(v||'').trim().toLowerCase().slice(0,32),validAccount=a=>/^[a-z0-9_.-]{4,32}$/.test(a),validPassword=p=>typeof p==='string'&&p.length>=4&&p.length<=72;
const CLASS_RANGES={royal:{str:[11,16],dex:[9,15],con:[10,16],int:[8,13],wis:[9,15],cha:[12,18]},knight:{str:[14,18],dex:[10,16],con:[14,18],int:[7,11],wis:[8,13],cha:[8,12]},mage:{str:[8,13],dex:[8,14],con:[8,14],int:[14,18],wis:[14,18],cha:[8,14]},elf:{str:[10,16],dex:[14,18],con:[10,16],int:[10,16],wis:[11,17],cha:[9,15]}};
const rint=(a,b)=>a+Math.floor(Math.random()*(b-a+1));
function rollClassStats(cls){const r=CLASS_RANGES[cls];if(!r)return null;const out={};for(const k of ['str','dex','con','int','wis','cha'])out[k]=rint(r[k][0],r[k][1]);return out}
function hashPassword(p,s){return crypto.scryptSync(p,Buffer.from(s,'hex'),64).toString('hex')}function makePassword(p){const salt=crypto.randomBytes(16).toString('hex');return{salt,hash:hashPassword(p,salt)}}function safeEqualHex(a,b){try{const x=Buffer.from(a,'hex'),y=Buffer.from(b,'hex');return x.length===y.length&&crypto.timingSafeEqual(x,y)}catch(_){return false}}
function send(ws,type,payload){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type,payload:payload||{}}))}function fail(ws,code,message){send(ws,'error',{code,message})}
async function initDb(){await db.query(`CREATE TABLE IF NOT EXISTS accounts(username VARCHAR(32) PRIMARY KEY,password_salt VARCHAR(64) NOT NULL,password_hash VARCHAR(256) NOT NULL,character_token VARCHAR(96) UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_login_at TIMESTAMPTZ)`);await db.query('CREATE INDEX IF NOT EXISTS idx_accounts_character_token ON accounts(character_token)');console.log('PostgreSQL account authentication ready')}
function buildRuntimeServer(){const sourcePath=path.join(__dirname,'server.js'),runtimePath=path.join(__dirname,'.server-runtime.js');let src=fs.readFileSync(sourcePath,'utf8');const a="function newCharacter(name,cls){const b=baseForClass(cls),stats=rollStats(cls);return";const b="function newCharacter(name,cls,rolledStats){const b=baseForClass(cls),stats=(rolledStats&&typeof rolledStats==='object')?rolledStats:rollStats(cls);return";const c='char=newCharacter(name,cls);',d='char=newCharacter(name,cls,p.stats);';if(!src.includes(a)||!src.includes(c))throw new Error('server.js creation hook signature changed');src=src.replace(a,b).replace(c,d);fs.writeFileSync(runtimePath,src);return runtimePath}
let runtimeServer;try{runtimeServer=buildRuntimeServer()}catch(e){console.error('Cannot prepare game runtime:',e);process.exit(1)}
const child=spawn(process.execPath,[runtimeServer],{cwd:__dirname,env:Object.assign({},process.env,{PORT:String(GAME_PORT),HOST:'127.0.0.1'}),stdio:'inherit'});child.on('exit',(code,signal)=>{console.error(`Game server exited code=${code} signal=${signal||''}`);process.exit(code||1)});
function openBackend(onOpen,onMessage,onClose,onError){const b=new WebSocket(BACKEND_URL,{maxPayload:MAX_MSG});b.on('open',()=>onOpen(b));b.on('message',d=>onMessage(b,d));b.on('close',()=>onClose&&onClose());b.on('error',e=>onError&&onError(e));return b}
async function authenticateAccount(account,password){const r=await db.query('SELECT username,password_salt,password_hash,character_token FROM accounts WHERE username=$1 LIMIT 1',[account]);if(!r.rows.length)return{error:'account_not_found'};const row=r.rows[0],candidate=hashPassword(password,row.password_salt);if(!safeEqualHex(candidate,row.password_hash))return{error:'wrong_password'};return{row}}
const server=http.createServer(async(req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');if(req.url==='/health'){try{const c=await db.query('SELECT COUNT(*)::int AS n FROM accounts');res.end(JSON.stringify({ok:true,world:'1.49',authority:'server',persistence:'postgresql',authentication:'postgresql-scrypt',creationRolls:'server-signed',accounts:c.rows[0].n}))}catch(_){res.statusCode=500;res.end(JSON.stringify({ok:false,error:'database_unavailable'}))}return}res.end(JSON.stringify({name:'MMO2 1.49 auth gateway',authentication:'postgresql-scrypt'}))});
const wss=new WebSocketServer({server,maxPayload:MAX_MSG});
wss.on('connection',client=>{let backend=null,authenticated=false,authInProgress=false;const rolls=new Map();
send(client,'welcome',{world:'1.49',authority:'server',authentication:'postgresql'});
function attach(token,registration){if(backend)try{backend.close()}catch(_){}let ready=false;backend=openBackend(ws=>{ready=true;ws.send(JSON.stringify({type:'auth',payload:registration?{token:'',name:registration.name,cls:registration.cls,stats:registration.stats}:{token}}))},async(ws,data)=>{let packet;try{packet=JSON.parse(data.toString())}catch(_){return}if(packet.type==='welcome')return;if(registration&&packet.type==='auth_ok'){const newToken=packet.payload&&packet.payload.token;if(!newToken){authInProgress=false;return fail(client,'registration_failed','建立角色失敗。')}const creds=makePassword(registration.password);try{await db.query('INSERT INTO accounts(username,password_salt,password_hash,character_token,last_login_at) VALUES($1,$2,$3,$4,NOW())',[registration.account,creds.salt,creds.hash,newToken])}catch(e){authInProgress=false;try{ws.close()}catch(_){};return fail(client,e&&e.code==='23505'?'account_exists':'registration_failed',e&&e.code==='23505'?'這個帳號已經有人使用。':'帳號建立失敗，請稍後再試。')}authenticated=true;authInProgress=false;packet.payload.account=registration.account;packet.payload.auth='postgresql';return send(client,packet.type,packet.payload)}if(!registration&&packet.type==='auth_ok'){authenticated=true;authInProgress=false;packet.payload.auth='postgresql';return send(client,packet.type,packet.payload)}if(packet.type==='error'&&!authenticated)authInProgress=false;if(client.readyState===WebSocket.OPEN)client.send(data.toString())},()=>{if(authenticated&&client.readyState===WebSocket.OPEN){fail(client,'game_backend_closed','遊戲伺服器連線中斷。');try{client.close()}catch(_){}}},()=>{if(!ready){authInProgress=false;fail(client,'game_backend_unavailable','遊戲伺服器啟動中，請稍後再試。')}})}
client.on('message',async raw=>{let msg;try{msg=JSON.parse(raw.toString())}catch(_){return}const p=msg.payload||{};
if(msg.type==='ping'&&!authenticated)return send(client,'pong',{t:Date.now()});
if(msg.type==='roll_stats'&&!authenticated){const cls=String(p.cls||'');const stats=rollClassStats(cls);if(!stats)return fail(client,'invalid_class','請先選擇職業。');const rollId=crypto.randomBytes(16).toString('hex');rolls.set(rollId,{cls,stats,expires:Date.now()+10*60*1000});for(const[id,r]of rolls)if(r.expires<Date.now())rolls.delete(id);return send(client,'roll_stats',{rollId,cls,stats});}
if(msg.type==='auth'){if(authInProgress)return;authInProgress=true;const legacyToken=String(p.token||'').trim().slice(0,96),account=cleanAccount(p.account),password=String(p.password||'');if(p.register===true){if(!validAccount(account)){authInProgress=false;return fail(client,'invalid_credentials','帳號需為 4～32 個英數字，可使用 . _ -。')}if(!validPassword(password)){authInProgress=false;return fail(client,'invalid_credentials','密碼需為 4～72 個字元。')}const name=String(p.name||'').trim().slice(0,12),cls=String(p.cls||''),rollId=String(p.rollId||'');const roll=rolls.get(rollId);if(name.length<2||!CLASS_RANGES[cls]){authInProgress=false;return fail(client,'invalid_character','請輸入 2～12 字角色名稱並選擇職業。')}if(!roll||roll.cls!==cls||roll.expires<Date.now()){authInProgress=false;return fail(client,'invalid_roll','請重新按「Server 擲骰」取得角色能力值。')}rolls.delete(rollId);const exists=await db.query('SELECT 1 FROM accounts WHERE username=$1 LIMIT 1',[account]);if(exists.rows.length){authInProgress=false;return fail(client,'account_exists','這個帳號已經有人使用。')}return attach('',{account,password,name,cls,stats:roll.stats})}if(account||password){if(!validAccount(account)||!validPassword(password)){authInProgress=false;return fail(client,'invalid_credentials','帳號或密碼格式不正確。')}try{const r=await authenticateAccount(account,password);if(r.error){authInProgress=false;return fail(client,r.error,r.error==='account_not_found'?'找不到這個帳號。':'帳號或密碼錯誤。')}await db.query('UPDATE accounts SET last_login_at=NOW() WHERE username=$1',[account]);return attach(r.row.character_token,null)}catch(_){authInProgress=false;return fail(client,'database_error','資料庫驗證失敗，請稍後再試。')}}if(legacyToken)return attach(legacyToken,null);authInProgress=false;return fail(client,'invalid_credentials','請輸入帳號與密碼。')}if(!authenticated||!backend||backend.readyState!==WebSocket.OPEN)return fail(client,'not_authenticated','請先登入帳號。');backend.send(raw.toString())});client.on('close',()=>{if(backend)try{backend.close()}catch(_){}})});
(async()=>{try{await initDb();server.listen(PORT,HOST,()=>console.log(`MMO2 auth gateway on ${HOST}:${PORT}; game backend ${BACKEND_URL}`))}catch(e){console.error('Auth gateway startup failed:',e);try{child.kill()}catch(_){}process.exit(1)}})();
async function shutdown(){try{child.kill('SIGTERM')}catch(_){}try{fs.unlinkSync(runtimeServer)}catch(_){}try{await db.end()}catch(_){}process.exit(0)}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
