'use strict';

const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Pool } = require('pg');
const { WebSocketServer, WebSocket } = require('ws');

const PORT = Number(process.env.PORT || 8080);
const HOST = process.env.HOST || '0.0.0.0';
const MAX_MSG = 16 * 1024;
const TICK_MS = 1000;
const SAVE_FILE = process.env.SAVE_FILE || path.join(__dirname, 'data', 'characters.json');
const DATABASE_URL = process.env.DATABASE_URL || '';
const db = DATABASE_URL ? new Pool({ connectionString:DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized:false } : undefined }) : null;

const clients = new Map();
const characters = new Map();
const dirtyTokens = new Set();
const worlds = new Map();
const ALLOWED_CLASSES = new Set(['royal','knight','mage','elf']);

const MAPS = {
  town_silver_knight:{name:'銀騎士村',safe:true}, town_elf:{name:'妖精森林',safe:true}, town_talking:{name:'說話之島',safe:true}, town_gludio:{name:'燃柳村',safe:true}, town_gludin:{name:'古魯丁村莊',safe:true},
  training:{name:'新兵修練場',pool:['orc','goblin','orc_archer','gremlin']}, silver_knight:{name:'銀騎士地區',pool:['orc','goblin','orc_archer','zombie','wolf','skeleton']}, talking_island:{name:'說話之島周邊',pool:['orc','goblin','orc_archer','zombie','wolf','skeleton']}, talking_island_port:{name:'說話之島港口',pool:['fighter','wolf','stone_golem','spider','b_knight','elder','kurt']}, zone_01:{name:'妖精森林周邊',pool:['orc','orc_archer','fighter','zombie','wolf','orc_mage','stone_golem']}, elf_forest:{name:'妖魔森林',pool:['orc_archer','fighter','wolf','orc_mage','ghoul','sparto','lycan','gaster']}, gludio:{name:'古魯丁',pool:['orc','goblin','zombie','fighter','wolf','skeleton','ghoul','sparto']}, windwood:{name:'風木',pool:['orc_archer','fighter','wolf','orc_mage','stone_golem','lizardman','ant']}, desert:{name:'沙漠',pool:['evil_lizard','scorpion','ant','giant_ant','lizardman','stone_golem','sparto']}, kent:{name:'肯特',pool:['orc','goblin','orc_archer','fighter','wolf','stone_golem','spider','hobgoblin','bear']},
  zone_06:{name:'古魯丁地監1樓',pool:['orc','orc_archer','zombie','fighter','skeleton','skel_archer','ghoul','sparto']}, zone_07:{name:'古魯丁地監2樓',pool:['zombie','skeleton','skel_archer','skel_spear','spider','ghoul','sparto']}, zone_08:{name:'古魯丁地監3樓',pool:['zombie','skeleton','skel_archer','stone_golem','ghoul','sparto','ogre']}, zone_09:{name:'古魯丁地監4樓',pool:['zombie','skeleton','skel_archer','ghoul','sparto','ogre','cerberus']}, zone_10:{name:'古魯丁地監5樓',pool:['skeleton','skel_archer','skel_axe','skel_spear','ghoul','sparto','cerberus','dk']}, zone_11:{name:'古魯丁地監6樓',pool:['skel_archer','ghoul','sparto','elder','ogre','cerberus','necromancer','dk']}, zone_12:{name:'古魯丁地監7樓',pool:['skel_archer','ghoul','sparto','ogre','cerberus','dk']}, zone_13:{name:'說話之島地監1樓',pool:['orc','zombie','fighter','skeleton','skel_archer','stone_golem','ghoul']}, zone_14:{name:'說話之島地監2樓',pool:['zombie','skeleton','skel_archer','ghoul','sparto','black_knight','kurt']}, zone_15:{name:'眠龍洞穴1樓',pool:['orc','zombie','skeleton','ghoul','sparto','lizardman']}, zone_16:{name:'眠龍洞穴2樓',pool:['skeleton','skel_archer','ghoul','sparto','lizardman','ogre']}, zone_17:{name:'眠龍洞穴3樓',pool:['skeleton','sparto','ogre','cerberus','dark_elf']}, zone_22:{name:'沙漠地監1樓',pool:['ant','giant_ant','scorpion','lizardman','skeleton']}, zone_23:{name:'沙漠地監2樓',pool:['ant','giant_ant','scorpion','sparto','skeleton']}, zone_24:{name:'沙漠地監3樓',pool:['giant_ant','scorpion','sparto','cerberus']}, zone_25:{name:'沙漠地監4樓',pool:['giant_ant','sparto','cerberus','ogre']}, zone_32:{name:'螞蟻洞窟1樓',pool:['ant','giant_ant','scorpion']}, zone_33:{name:'螞蟻洞窟2樓',pool:['giant_ant','scorpion','ant_queen']}, dragon_valley:{name:'龍之谷',pool:['sparto','lycan','scorpion','harpy','dark_elf','ogre_warrior','arian','wyvern','blackelder']}, zone_26:{name:'龍之谷地監1樓',pool:['skeleton','skel_archer','sparto','ghoul','cerberus']}, zone_27:{name:'龍之谷地監2樓',pool:['skeleton','skel_archer','sparto','cerberus','ogre']}, zone_28:{name:'龍之谷地監3樓',pool:['skel_archer','sparto','cerberus','ogre','dark_elf']}, zone_29:{name:'龍之谷地監4樓',pool:['sparto','cerberus','ogre','dark_elf','wyvern']}, zone_30:{name:'龍之谷地監5樓',pool:['cerberus','ogre','dark_elf','wyvern','blackelder']}, zone_31:{name:'龍之谷地監6樓',pool:['ogre','dark_elf','wyvern','blackelder','dragon']}
};
const ALLOWED_MAPS = new Set(Object.keys(MAPS));
const MOB_STATS={orc:[5,35,5,3],goblin:[3,24,3,2],orc_archer:[6,32,6,3],gremlin:[4,28,4,2],zombie:[7,45,6,3],wolf:[5,30,5,3],skeleton:[8,48,7,4],fighter:[9,55,8,4],stone_golem:[12,95,11,6],spider:[8,50,7,4],ghoul:[12,80,10,5],sparto:[15,105,13,7],lycan:[17,120,14,8],gaster:[18,130,15,8],orc_mage:[14,88,12,6],hobgoblin:[13,90,11,6],bear:[16,125,14,8],lizardman:[18,130,15,8],ant:[10,60,9,5],giant_ant:[17,125,14,8],scorpion:[18,135,15,8],evil_lizard:[16,115,14,7],skel_archer:[14,85,12,6],skel_spear:[16,105,13,7],skel_axe:[17,115,14,7],ogre:[22,230,22,13],cerberus:[24,250,24,14],elder:[25,210,22,13],necromancer:[30,320,28,18],dk:[35,520,36,24],black_knight:[24,240,22,14],b_knight:[24,240,22,14],kurt:[30,420,31,20],dark_elf:[28,280,26,17],ogre_warrior:[30,360,29,18],arian:[32,390,31,20],wyvern:[34,430,34,22],blackelder:[38,560,40,26],dragon:[42,700,48,32],ant_queen:[30,450,32,21]};

// 伺服器自己的 1.49 道具真實資料。瀏覽器 DB.items 只負責圖示與文字顯示。
const ITEM_CATALOG = {
  potion_red:{name:'紅色藥水',type:'consumable',price:45,heal:[10,20],stack:true},
  potion_orange:{name:'橙色藥水',type:'consumable',price:180,heal:[25,45],stack:true},
  potion_clear:{name:'透明藥水',type:'consumable',price:550,heal:[55,85],stack:true},
  wpn_5:{name:'箭',type:'ammo',price:1,stack:true},
  wpn_22:{name:'銀箭',type:'ammo',price:2,stack:true},
  scroll_weapon:{name:'對武器施法的卷軸',type:'scroll',price:30000,stack:true},
  scroll_armor:{name:'對盔甲施法的卷軸',type:'scroll',price:30000,stack:true},
  item_dagger:{name:'匕首',type:'weapon',slot:'wpn',price:50,atk:2},
  item_sword:{name:'長劍',type:'weapon',slot:'wpn',price:900,atk:4},
  item_bow:{name:'獵人之弓',type:'weapon',slot:'wpn',price:1200,atk:3},
  item_staff:{name:'魔杖',type:'weapon',slot:'wpn',price:1000,atk:1,sp:1},
  item_leather_armor:{name:'皮甲',type:'armor',slot:'armor',price:700,ac:2},
  item_chain_mail:{name:'鎖子甲',type:'armor',slot:'armor',price:3500,ac:4},
  item_helmet:{name:'頭盔',type:'armor',slot:'helm',price:800,ac:1},
  item_shield:{name:'盾牌',type:'armor',slot:'shield',price:1000,ac:2},
  skillbook_light:{name:'魔法書(光箭)',type:'skillbook',price:1000,skill:'sk_light_arrow'},
  skillbook_heal:{name:'魔法書(初級治癒術)',type:'skillbook',price:1200,skill:'sk_heal'}
};
const SHOP_ITEMS = new Set(Object.keys(ITEM_CATALOG).filter(id=>ITEM_CATALOG[id].price>0));
const DROP_TABLE = {
  goblin:[['potion_red',0.08,1]], orc:[['potion_red',0.06,1],['wpn_5',0.12,10]], zombie:[['potion_red',0.05,1]],
  skeleton:[['scroll_armor',0.003,1]], skel_archer:[['wpn_22',0.08,10]], ghoul:[['potion_orange',0.04,1]],
  sparto:[['scroll_weapon',0.004,1]], ogre:[['potion_clear',0.08,1],['item_chain_mail',0.005,1]],
  dark_elf:[['potion_clear',0.06,1],['scroll_weapon',0.008,1]], wyvern:[['scroll_armor',0.01,1]], blackelder:[['scroll_weapon',0.015,1],['scroll_armor',0.015,1]],
  kurt:[['item_sword',0.08,1]], ant_queen:[['scroll_armor',0.05,1]], dk:[['item_sword',0.03,1]]
};
const CLASS_SKILLS={royal:['sk_light_arrow'],knight:[],mage:['sk_light_arrow','sk_heal'],elf:['sk_light_arrow']};

function cleanText(v,max){return String(v==null?'':v).replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,max);}
function rint(lo,hi){return lo+Math.floor(Math.random()*(hi-lo+1));}
function clamp(v,lo,hi){v=Number(v);return Number.isFinite(v)?Math.max(lo,Math.min(hi,v)):lo;}
function uid(prefix='i'){return prefix+crypto.randomBytes(9).toString('hex');}
function send(ws,type,payload){if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type,payload}));}
function error(ws,message){send(ws,'error',{message});}
function markDirty(token){if(token)dirtyTokens.add(token);}
function baseForClass(cls){return {royal:{hp:70,mp:20,atk:8,ac:2},knight:{hp:95,mp:8,atk:11,ac:4},mage:{hp:50,mp:55,atk:5,ac:0},elf:{hp:60,mp:30,atk:8,ac:2}}[cls]||{hp:70,mp:20,atk:8,ac:2};}
function rollStats(cls){const p={royal:{str:[11,16],dex:[9,15],con:[10,16],int:[8,13],wis:[9,15],cha:[12,18]},knight:{str:[14,18],dex:[10,16],con:[14,18],int:[7,11],wis:[8,13],cha:[8,12]},mage:{str:[8,13],dex:[8,14],con:[8,14],int:[14,18],wis:[14,18],cha:[8,14]},elf:{str:[10,16],dex:[14,18],con:[10,16],int:[10,16],wis:[11,17],cha:[9,15]}}[cls];let s={};for(const k of ['str','dex','con','int','wis','cha'])s[k]=rint(p[k][0],p[k][1]);return s;}
function starterItems(cls){const out=[];const add=(id,cnt=1)=>out.push({uid:uid(),id,cnt,en:0,bless:false,lock:false});add('potion_red',10);if(cls==='knight'||cls==='royal')add('item_sword');else if(cls==='elf'){add('item_bow');add('wpn_5',500);}else add('item_staff');add('item_leather_armor');return out;}
function newCharacter(name,cls){const b=baseForClass(cls),stats=rollStats(cls);return{name,cls,lv:1,exp:0,gold:1000,hp:b.hp,maxHp:b.hp,mp:b.mp,maxMp:b.mp,baseAtk:b.atk,baseAc:b.ac,stats,map:cls==='elf'?'town_elf':(cls==='knight'?'town_silver_knight':'town_talking'),pos:{x:0,y:0},deaths:0,inventory:starterItems(cls),equipment:{wpn:null,armor:null,helm:null,shield:null,arrow:null},skills:(CLASS_SKILLS[cls]||[]).slice(),quests:{},warehouse:[],flags:{serverAuthoritative:true},updatedAt:Date.now()};}
function normalizeItem(i){if(!i||!ITEM_CATALOG[i.id])return null;return{uid:cleanText(i.uid||uid(),32),id:i.id,cnt:Math.max(1,Math.min(999999,Math.floor(Number(i.cnt)||1))),en:Math.max(0,Math.min(20,Math.floor(Number(i.en)||0))),bless:i.bless===true?'blessed':(i.bless==='cursed'?'cursed':false),lock:!!i.lock};}
function normalizeChar(c){if(!c||!ALLOWED_CLASSES.has(c.cls))return null;if(!ALLOWED_MAPS.has(c.map))c.map=c.cls==='elf'?'town_elf':(c.cls==='knight'?'town_silver_knight':'town_talking');if(!c.stats)c.stats=rollStats(c.cls);if(!Array.isArray(c.inventory))c.inventory=starterItems(c.cls);c.inventory=c.inventory.map(normalizeItem).filter(Boolean);if(!c.equipment||typeof c.equipment!=='object')c.equipment={wpn:null,armor:null,helm:null,shield:null,arrow:null};if(!Array.isArray(c.skills))c.skills=(CLASS_SKILLS[c.cls]||[]).slice();if(!c.quests||typeof c.quests!=='object')c.quests={};if(!Array.isArray(c.warehouse))c.warehouse=[];if(!c.pos)c.pos={x:0,y:0};if(c.baseAtk==null)c.baseAtk=baseForClass(c.cls).atk;if(c.baseAc==null)c.baseAc=baseForClass(c.cls).ac;c.flags={serverAuthoritative:true};recalc(c);return c;}
function findInv(c,itemUid){return c.inventory.find(i=>i.uid===itemUid)||null;}
function addItem(c,id,cnt=1,opts={}){const d=ITEM_CATALOG[id];if(!d||cnt<=0)return null;cnt=Math.max(1,Math.min(999999,Math.floor(cnt)));if(d.stack){let ex=c.inventory.find(i=>i.id===id&&i.en===(opts.en||0)&&i.bless===(opts.bless||false));if(ex){ex.cnt+=cnt;return ex;}}const it={uid:uid(),id,cnt,en:Math.max(0,Math.floor(opts.en||0)),bless:opts.bless||false,lock:false};c.inventory.push(it);return it;}
function removeItem(c,itemUid,cnt=1){const i=c.inventory.findIndex(x=>x.uid===itemUid);if(i<0)return null;const it=c.inventory[i],n=Math.max(1,Math.floor(cnt));if(it.cnt<n)return null;if(it.cnt===n)c.inventory.splice(i,1);else it.cnt-=n;return it;}
function itemEquipped(c,itemUid){for(const [slot,u] of Object.entries(c.equipment))if(u===itemUid)return slot;return null;}
function recalc(c){let atk=c.baseAtk+Math.floor((c.stats.str||10)/4),ac=c.baseAc+Math.floor((c.stats.dex||10)/6),sp=Math.floor((c.stats.int||10)/5);for(const u of Object.values(c.equipment||{})){if(!u)continue;const it=findInv(c,u),d=it&&ITEM_CATALOG[it.id];if(!d)continue;atk+=(d.atk||0)+(it.en||0);ac+=(d.ac||0)+(d.type==='armor'?(it.en||0):0);sp+=(d.sp||0);}c.atk=atk;c.ac=ac;c.sp=sp;return c;}

async function initPersistence(){if(db){await db.query(`CREATE TABLE IF NOT EXISTS characters (token VARCHAR(96) PRIMARY KEY, name VARCHAR(24) NOT NULL, class VARCHAR(16) NOT NULL, data JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);const result=await db.query('SELECT token,data FROM characters');for(const row of result.rows){const c=normalizeChar(row.data);if(c)characters.set(row.token,c);}console.log(`PostgreSQL persistence ready: ${characters.size} character(s) loaded`);return;}try{const raw=JSON.parse(fs.readFileSync(SAVE_FILE,'utf8'));for(const[token,value]of Object.entries(raw||{})){const c=normalizeChar(value);if(c)characters.set(token,c);}}catch(_){}console.warn('DATABASE_URL not set; using local JSON fallback.');}
async function saveToken(token){const c=characters.get(token);if(!c)return;if(db){await db.query(`INSERT INTO characters(token,name,class,data,updated_at) VALUES($1,$2,$3,$4::jsonb,NOW()) ON CONFLICT(token) DO UPDATE SET name=EXCLUDED.name,class=EXCLUDED.class,data=EXCLUDED.data,updated_at=NOW()`,[token,c.name,c.cls,JSON.stringify(c)]);}}
async function flushDirty(){if(!dirtyTokens.size)return;const tokens=Array.from(dirtyTokens);dirtyTokens.clear();if(db){for(const token of tokens){try{await saveToken(token);}catch(e){dirtyTokens.add(token);console.error('PostgreSQL save failed',e.message);}}return;}try{fs.mkdirSync(path.dirname(SAVE_FILE),{recursive:true});const tmp=SAVE_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(Object.fromEntries(characters.entries()),null,2));fs.renameSync(tmp,SAVE_FILE);}catch(e){console.error('JSON save failed',e);}}
setInterval(()=>{flushDirty().catch(console.error);},2000).unref();

function expNeed(lv){return 100+Math.max(0,lv-1)*80;}
function checkLevel(c){while(c.lv<99&&c.exp>=expNeed(c.lv)){c.exp-=expNeed(c.lv);c.lv++;const b=baseForClass(c.cls);c.maxHp+=Math.max(4,Math.floor(b.hp/14))+Math.floor((c.stats.con||10)/8);c.maxMp+=Math.max(1,Math.floor(b.mp/14))+Math.floor((c.stats.wis||10)/10);c.baseAtk+=(c.lv%2===0?1:0);c.hp=c.maxHp;c.mp=c.maxMp;}recalc(c);}
function publicInventory(c){return c.inventory.map(i=>Object.assign({},i,{server:true}));}
function publicChar(c,id){return{id,name:c.name,cls:c.cls,lv:c.lv,hp:c.hp,maxHp:c.maxHp,mp:c.mp,maxMp:c.maxMp,gold:c.gold,exp:c.exp,expNeed:expNeed(c.lv),map:c.map,pos:c.pos,stats:c.stats,atk:c.atk,ac:c.ac,sp:c.sp,inventory:publicInventory(c),equipment:Object.assign({},c.equipment),skills:c.skills.slice(),quests:c.quests,warehouse:c.warehouse,flags:c.flags};}
function clientChar(client){return client&&client.token?characters.get(client.token):null;}
function worldFor(mapId){if(!worlds.has(mapId))worlds.set(mapId,{map:mapId,mobs:[],seq:0});const w=worlds.get(mapId);ensureMobs(w);return w;}
function makeMob(mapId,world){const pool=(MAPS[mapId]&&MAPS[mapId].pool)||[];if(!pool.length)return null;const templateId=pool[rint(0,pool.length-1)],s=MOB_STATS[templateId]||[10,70,9,5];world.seq++;return{uid:'m'+world.seq+'-'+crypto.randomBytes(3).toString('hex'),templateId,lv:s[0],hp:s[1],maxHp:s[1],atk:s[2],def:s[3],dead:false,respawnAt:0};}
function ensureMobs(world){const map=MAPS[world.map];if(!map||map.safe){world.mobs.length=0;return;}for(let i=0;i<3;i++)if(!world.mobs[i])world.mobs[i]=makeMob(world.map,world);}
function publicWorld(world){return{map:world.map,name:(MAPS[world.map]||{}).name||world.map,mobs:world.mobs.filter(Boolean).map(m=>({uid:m.uid,templateId:m.templateId,lv:m.lv,hp:m.hp,maxHp:m.maxHp,dead:m.dead}))};}
function playersInMap(mapId){const out=[];for(const cl of clients.values()){const ch=clientChar(cl);if(ch&&ch.map===mapId)out.push(cl);}return out;}
function sendSnapshot(client,event){const c=clientChar(client);if(!c)return;send(client.ws,'snapshot',{self:publicChar(c,client.id),world:publicWorld(worldFor(c.map)),event:event||null});}
function broadcastMap(mapId,event){for(const cl of playersInMap(mapId))sendSnapshot(cl,event);}
function presence(){const players=[];for(const cl of clients.values()){const ch=clientChar(cl);if(ch)players.push({id:cl.id,name:ch.name,cls:ch.cls,lv:ch.lv,map:ch.map,pos:ch.pos,hp:ch.hp,maxHp:ch.maxHp});}for(const cl of clients.values())send(cl.ws,'presence',{players});}
function commit(client,event){const c=clientChar(client);if(!c)return;markDirty(client.token);c.updatedAt=Date.now();sendSnapshot(client,event);}

async function handleLogin(client,p){let token=cleanText(p.token,80),char=token&&characters.get(token);if(!char){const name=cleanText(p.name,12),cls=ALLOWED_CLASSES.has(p.cls)?p.cls:null;if(name.length<2||!cls)return error(client.ws,'首次連線需要 2～12 字角色名稱與四大職業。');token=crypto.randomBytes(24).toString('hex');char=newCharacter(name,cls);characters.set(token,char);markDirty(token);await flushDirty();}else normalizeChar(char);client.token=token;client.lastSeen=Date.now();send(client.ws,'auth_ok',{token,character:publicChar(char,client.id)});sendSnapshot(client,{type:'login'});presence();}
function handleMapChange(client,p){const c=clientChar(client);if(!c)return;const target=cleanText(p.map,40);if(!ALLOWED_MAPS.has(target))return error(client.ws,'1.49 世界不存在這張地圖。');const from=c.map;c.map=target;c.pos={x:0,y:0};if(MAPS[target].safe){c.hp=c.maxHp;c.mp=c.maxMp;}commit(client,{type:'map_change',from,to:target});broadcastMap(from,{type:'player_leave_map',id:client.id});broadcastMap(target,{type:'player_enter_map',id:client.id,name:c.name});presence();}
function handleMove(client,p){const c=clientChar(client);if(!c)return;if((client.nextMoveAt||0)>Date.now())return;client.nextMoveAt=Date.now()+80;c.pos={x:clamp(p.x,-10000,10000),y:clamp(p.y,-10000,10000)};markDirty(client.token);for(const cl of playersInMap(c.map))send(cl.ws,'player_move',{id:client.id,name:c.name,map:c.map,x:c.pos.x,y:c.pos.y});}
function rollDrops(mob){const rows=DROP_TABLE[mob.templateId]||[];const out=[];for(const [id,chance,cnt] of rows)if(Math.random()<chance)out.push({id,cnt});return out;}
function handleAttack(client,p){const c=clientChar(client);if(!c||c.hp<=0)return;const map=MAPS[c.map];if(!map||map.safe)return;const world=worldFor(c.map),mob=world.mobs.find(m=>m&&!m.dead&&m.uid===p.uid);if(!mob)return error(client.ws,'目標已不存在。');if((client.nextAttackAt||0)>Date.now())return;client.nextAttackAt=Date.now()+Math.max(450,900-c.lv*4);recalc(c);const hitChance=Math.max(0.45,Math.min(0.95,0.72+(c.lv-mob.lv)*0.012+(c.stats.dex-10)*0.004));let dmg=0,hit=Math.random()<hitChance;if(hit){dmg=Math.max(1,rint(Math.max(1,c.atk-3),c.atk+5)-Math.floor(mob.def/3));mob.hp=Math.max(0,mob.hp-dmg);}const evt={type:'attack',attacker:client.id,target:mob.uid,hit,dmg};if(mob.hp<=0&&!mob.dead){mob.dead=true;mob.respawnAt=Date.now()+5000;const exp=Math.max(5,mob.lv*7),gold=rint(Math.max(1,mob.lv*2),Math.max(3,mob.lv*5));c.exp+=exp;c.gold+=gold;const drops=rollDrops(mob);for(const d of drops)addItem(c,d.id,d.cnt);checkLevel(c);evt.kill=true;evt.exp=exp;evt.gold=gold;evt.drops=drops;markDirty(client.token);}broadcastMap(c.map,evt);}
function handleEquip(client,p){const c=clientChar(client);if(!c)return;const it=findInv(c,cleanText(p.uid,40)),d=it&&ITEM_CATALOG[it.id];if(!it||!d||!d.slot)return error(client.ws,'無法裝備這個物品。');let slot=d.slot;if(slot==='arrow')slot='arrow';const old=c.equipment[slot];c.equipment[slot]=it.uid;recalc(c);commit(client,{type:'equip',slot,uid:it.uid,old});}
function handleUnequip(client,p){const c=clientChar(client);if(!c)return;const slot=cleanText(p.slot,20);if(!(slot in c.equipment))return;c.equipment[slot]=null;recalc(c);commit(client,{type:'unequip',slot});}
function handleUseItem(client,p){const c=clientChar(client);if(!c||c.hp<=0)return;const it=findInv(c,cleanText(p.uid,40)),d=it&&ITEM_CATALOG[it.id];if(!it||!d)return error(client.ws,'找不到物品。');if(d.heal){const before=c.hp;c.hp=Math.min(c.maxHp,c.hp+rint(d.heal[0],d.heal[1]));removeItem(c,it.uid,1);commit(client,{type:'use_item',id:it.id,heal:c.hp-before});return;}if(d.type==='skillbook'){if(!c.skills.includes(d.skill))c.skills.push(d.skill);removeItem(c,it.uid,1);commit(client,{type:'learn_skill',skill:d.skill});return;}error(client.ws,'此物品尚未支援伺服器使用。');}
function handleBuy(client,p){const c=clientChar(client);if(!c)return;if(!MAPS[c.map]||!MAPS[c.map].safe)return error(client.ws,'只有安全區可以購物。');const id=cleanText(p.id,80),d=ITEM_CATALOG[id];const qty=Math.max(1,Math.min(9999,Math.floor(Number(p.qty)||1)));if(!d||!SHOP_ITEMS.has(id))return error(client.ws,'商店沒有這項商品。');const cost=d.price*qty;if(c.gold<cost)return error(client.ws,'金幣不足。');c.gold-=cost;addItem(c,id,qty);commit(client,{type:'buy',id,qty,cost});}
function handleSell(client,p){const c=clientChar(client);if(!c)return;if(!MAPS[c.map]||!MAPS[c.map].safe)return error(client.ws,'只有安全區可以販賣。');const it=findInv(c,cleanText(p.uid,40)),d=it&&ITEM_CATALOG[it.id];if(!it||!d)return;const qty=Math.max(1,Math.min(it.cnt,Math.floor(Number(p.qty)||1)));if(itemEquipped(c,it.uid))return error(client.ws,'請先卸下裝備。');const gain=Math.max(1,Math.floor((d.price||1)*0.4))*qty;removeItem(c,it.uid,qty);c.gold+=gain;commit(client,{type:'sell',id:it.id,qty,gain});}
function handleWarehouse(client,p){const c=clientChar(client);if(!c)return;if(!MAPS[c.map]||!MAPS[c.map].safe)return error(client.ws,'只有安全區可以使用倉庫。');if(p.action==='deposit'){const it=findInv(c,cleanText(p.uid,40));if(!it||itemEquipped(c,it.uid))return;const n=Math.max(1,Math.min(it.cnt,Math.floor(Number(p.qty)||1)));const copy=Object.assign({},it,{uid:uid(),cnt:n});removeItem(c,it.uid,n);c.warehouse.push(copy);commit(client,{type:'warehouse_deposit',id:copy.id,qty:n});}else if(p.action==='withdraw'){const i=c.warehouse.findIndex(x=>x.uid===cleanText(p.uid,40));if(i<0)return;const it=c.warehouse[i],n=Math.max(1,Math.min(it.cnt,Math.floor(Number(p.qty)||1)));addItem(c,it.id,n,{en:it.en,bless:it.bless});if(it.cnt===n)c.warehouse.splice(i,1);else it.cnt-=n;commit(client,{type:'warehouse_withdraw',id:it.id,qty:n});}}
function handleQuest(client,p){const c=clientChar(client);if(!c)return;const key=cleanText(p.key,64);if(!key)return;const old=c.quests[key]||{state:'none',progress:0};if(p.action==='accept'&&old.state==='none')c.quests[key]={state:'active',progress:0};else if(p.action==='abandon')delete c.quests[key];else return;commit(client,{type:'quest',key,state:c.quests[key]||null});}
function handleChat(client,p){const c=clientChar(client);if(!c)return;const now=Date.now();if(now-(client.chatAt||0)<500)return;client.chatAt=now;const text=cleanText(p.text,80);if(!text)return;for(const x of clients.values())send(x.ws,'world_chat',{id:client.id,name:c.name,text,at:now});}

function worldTick(){const now=Date.now();for(const [mapId,world] of worlds.entries()){ensureMobs(world);let changed=false;for(let i=0;i<world.mobs.length;i++){const m=world.mobs[i];if(!m)continue;if(m.dead&&now>=m.respawnAt){world.mobs[i]=makeMob(mapId,world);changed=true;}}const pcs=playersInMap(mapId).filter(cl=>{const c=clientChar(cl);return c&&c.hp>0;}),alive=world.mobs.filter(m=>m&&!m.dead);if(pcs.length&&alive.length){for(const mob of alive){if(Math.random()>0.58)continue;const victim=pcs[rint(0,pcs.length-1)],c=clientChar(victim);recalc(c);const dmg=Math.max(1,rint(Math.max(1,mob.atk-4),mob.atk+3)-Math.floor(c.ac/2));c.hp=Math.max(0,c.hp-dmg);markDirty(victim.token);changed=true;if(c.hp===0){c.deaths=(c.deaths||0)+1;c.gold=Math.max(0,c.gold-Math.floor(c.gold*0.03));markDirty(victim.token);setTimeout(()=>{const cc=clientChar(victim);if(!cc)return;cc.map=cc.cls==='elf'?'town_elf':(cc.cls==='knight'?'town_silver_knight':'town_talking');cc.pos={x:0,y:0};cc.hp=cc.maxHp;cc.mp=cc.maxMp;markDirty(victim.token);sendSnapshot(victim,{type:'revive'});presence();},3000);}}}if(changed)broadcastMap(mapId,{type:'tick'});}}
setInterval(worldTick,TICK_MS).unref();

const server=http.createServer((req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Content-Type','application/json; charset=utf-8');if(req.url==='/health'){res.end(JSON.stringify({ok:true,online:clients.size,world:'1.49',authority:'server',persistence:db?'postgresql':'json-fallback',characters:characters.size,lastMap:'dragon_valley',authoritative:['stats','inventory','equipment','skills','quests','warehouse','position','maps','mobs','combat','drops','gold','exp','shops']}));return;}res.end(JSON.stringify({name:'MMO2 1.49 authoritative realtime server',online:clients.size,maps:Object.keys(MAPS).length,persistence:db?'postgresql':'json-fallback'}));});
const wss=new WebSocketServer({server,maxPayload:MAX_MSG});
wss.on('connection',ws=>{const id=crypto.randomUUID(),client={id,ws,token:null,lastSeen:Date.now(),chatAt:0,nextAttackAt:0,nextMoveAt:0};clients.set(id,client);send(ws,'welcome',{id,world:'1.49',authority:'server',lastMap:'dragon_valley'});ws.on('message',raw=>{client.lastSeen=Date.now();let msg;try{msg=JSON.parse(raw.toString());}catch(_){return;}const p=(msg&&msg.payload)||{};if(msg.type==='auth')return void handleLogin(client,p);if(!client.token)return error(ws,'尚未登入角色。');if(msg.type==='map_change')return handleMapChange(client,p);if(msg.type==='move')return handleMove(client,p);if(msg.type==='attack')return handleAttack(client,p);if(msg.type==='equip')return handleEquip(client,p);if(msg.type==='unequip')return handleUnequip(client,p);if(msg.type==='use_item')return handleUseItem(client,p);if(msg.type==='buy')return handleBuy(client,p);if(msg.type==='sell')return handleSell(client,p);if(msg.type==='warehouse')return handleWarehouse(client,p);if(msg.type==='quest')return handleQuest(client,p);if(msg.type==='world_chat')return handleChat(client,p);if(msg.type==='ping')return send(ws,'pong',{t:Date.now()});});ws.on('close',()=>{const c=clientChar(client),map=c&&c.map;clients.delete(id);if(map)broadcastMap(map,{type:'player_disconnect',id});presence();});});
setInterval(()=>{const now=Date.now();for(const c of clients.values())if(now-c.lastSeen>60000)try{c.ws.terminate();}catch(_){}},15000).unref();

(async()=>{try{await initPersistence();server.listen(PORT,HOST,()=>console.log(`MMO2 1.49 authoritative server on ${HOST}:${PORT}`));}catch(e){console.error('Fatal persistence init error:',e);process.exit(1);}})();
process.on('SIGINT',async()=>{await flushDirty();if(db)await db.end();process.exit(0);});
process.on('SIGTERM',async()=>{await flushDirty();if(db)await db.end();process.exit(0);});
